handshake-org/hsd

lib/node/http.js

The coin address endpoint at `./lib/node/http.js` passes an address string to `this.node.getCoinsByAddress(*)`, which eventually passes that same address to the mempool's `getCoinsByAddress(*)`. Attempting to query an address from the CLI or from CURL via `hsd-cli coin $ADDRESS` results in the error message `object is not an address`.
This PR creates an `Address` object after receiving the address string to fix this issue.

lib/node: use an address object in the coin address endpoint [bugfix]

---

lib/node/http.js

Across all implementations, we have decided to explore deprecating
the bulk read endpoints for coins/txs by address. See the discussion
here: https://github.com/bcoin-org/bcoin/pull/612 and here: https://github.com/bcoin-org/bcoin/issues/589.

http: include warning of deprecation for bulk reads

---

.npmignore

fix from @boymanjor 's bundle branch based off use with bpanel. Fixes error where bundling would fail when hsd is installed as a module because it can't find the ignored jsons.

remove names and tld from npmignore

---

lib/ui/amount.js

The exponents for `toMilli` and `fromMilli` didn't match. Following bcoin's `Amount.toMBTC` ([here](https://github.com/bcoin-org/bcoin/blob/85ed59c842f2aa4c1a8154d74a9cad7696cdfee3/lib/btc/amount.js#L90)), `toMilli` should encode the amount with exponent `5` instead of `4`.

update toMilli exponent to 3

---

lib/dns/records.js

Right now if an Addr record is added without a whitelisted name (handshake, bitcoin, ethereum) then we get an assertion error as bw is not passed into writeNameBW. This just adds it back in.

add missing bw

---

CHANGELOG.md
lib/wallet/wallet.js
test/wallet-test.js

This is a cherry-pick of https://github.com/bcoin-org/bcoin/pull/639
> Addresses #636 in which a user creates private keys they could never access due to a wallet being watch-only.
> 
> This PR goes along with #637 and [bcoin-org/bclient#15](https://github.com/bcoin-org/bclient/pull/15), maybe we can decide if we need all three safeties in place or which ones we do or don't need.
> 
> In this pull request, we prevent a watch-only wallet from ever generating a master (private) key which could lead to a user seeing addresses they can not spend from.
> 
> I think `watchOnly` should always require an `accountKey`. The reverse isn't necessarily required, for example in `bclient`, creating a wallet with `accountKey` automatically sets `watchOnly` to `true`. In bcoin `wallet._createAccount()`, …

Wallet: require public key for watchonly 

---

lib/node/http.js
lib/wallet/http.js

Cherry-picked from https://github.com/bcoin-org/bcoin/pull/603
> I dunno if this helpful for anyone else, but when playing with socket testing I noticed that both wallet and node http servers report some identical messages like `(http) Successful auth from 127.0.0.1.` but I wasn't sure which server I was hitting.
> 
> This PR simply changes the log context identifiers to `node-http` and `wallet-http` instead of just `http`
Example log: 
```
[debug] (node-http) Request for method=GET path=/ (127.0.0.1).
...
[debug] (wallet-http) Request for method=GET path=/wallet (127.0.0.1).
...
[debug] (wallet-http) Request for method=GET path=/wallet (127.0.0.1).
```

http: identify node/wallet in log

---

lib/primitives/mtx.js
lib/wallet/layout.js
lib/wallet/rpc.js
lib/wallet/wallet.js

This PR introduces new RPC calls, for each covenant type, which create unsigned txs to be signed offline. This PR also introduces a paths object to the MTX class. This object is used to indicate the HD paths of the signing keys. The MTX class has also been updated to persist coin information during de/serialization.
This functionality allows hardware wallet signing. End-to-end tests can be found in [hsd-ledger][hsd-ledger] and require a Ledger Nanos S hardware wallet.
This PR supersedes #90.
[hsd-ledger]: https://github.com/boymanjor/hsd-ledger/blob/master/test/e2e/hsd-test.js

wallet: support the creation of unsigned auction txs

---

README.md

Documents to use Node.js v10 right at the top of the `README.md`
There have been multiple issues that people were having that could have to do with the version of Node.js that they were running.
See:
https://github.com/handshake-org/hsd/issues/41
https://github.com/handshake-org/hsd/issues/28

readme: document minimum node.js version

---

lib/wallet/walletdb.js

This pull request removes dead code left over from `bcoin` in the `WalletDB`.
The `walletdb.witness` value was initially set to `false`, which doesn't make sense
in the context of Handshake.  I searched through the code for places where the
`witness` value could be referenced from outside the `WalletDB` class and could
not find any. The tests all still pass

walletdb: remove references to witness

---

lib/primitives/keyring.js

This pull request deletes some left over values in the `Keyring.fromJSON` method from bcoin.
See this for their original usage:
https://github.com/bcoin-org/bcoin/blob/2b2e53d83d4def08d25a2ed5c17c5638c3efa7b7/lib/primitives/keyring.js#L791

keyring: delete left over assertions from bcoin

---

.circleci/config.yml
package.json
test/node-test.js

This adds CI using Circle CI, copied directly from bcoin
at commit df1e8c06216f919d90c86cc89784f4c65d66eff3
The Circle CI project needs to be registered still
It would be really helpful if a project admin could go here to set it up:
https://circleci.com/add-projects/gh/handshake-org

test: add ci

---

etc/sample.conf
lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/node/fullnode.js

This PR removes the coin-cache from the blockchain. It was determined that using the coin-cache actually slows down the initial block download and can be easily configured in such a way that it crashes Node.js. This is a port of work done by braydonf on bcoin.
See relevant comment from jj:
https://github.com/bcoin-org/bcoin/issues/626#issuecomment-442059074
See PR on bcoin here: https://github.com/bcoin-org/bcoin/pull/736
Thank you at @braydonf for doing great work on `bcoin` regarding this issue

blockchain: remove coin-cache

---

test/chain-test.js
test/http-test.js
test/node-test.js

This commit updates the values expected from the `chain.db.value` in the chain and node tests. The block reward was increased from 1000 to 2000 at commit 601267d1b598617a4eb2cde7b906ab89c45c377c. This commit also updates the expected blocktemplate mintime which was updated in commit be4331fc8d63addb8e5fa6722ad29ac2a922b852.

test: fix values from updated block reward

---

.circleci/config.yml

This commit adds babel-eslint to the circle ci install script. The handshake parser was updated to babel-eslint in commit 726f7317939c679066c3cc27fb768673b7ca7d4a.

ci: install babel-eslint

---

bin/cli

Simple fix for the warning message to give the correct installation command. It was still instructing users to install `bclient` when instead it should instruct users to install `hs-client`

cli: fix typo

---

lib/mempool/mempool.js

The `prematureWitness` options isn't used anywhere in the codebase besides in these places. It is initialized, the type is asserted and then a value is set. It is not relevant to the Handshake codebase

mempool: remove premature witness option

---

bin/spvnode
bin/wallet
package.json

This is a cherry-pick of https://github.com/bcoin-org/bcoin/pull/652
(fullnode already parses `--no-wallet`)
...which also relies on a needed backport from bcoin: https://github.com/bcoin-org/bcoin/commit/d25e553605eaa8e8a55a04aacec0e238bc0e111d
and the more subtle: https://github.com/bcoin-org/bcoin/commit/2efa5275d53c8f2efbb4c1af638ce9ac85889520
...which are included in this PR.
Launch hsd full or spv with no wallet plugin:
`$ hsd --spv --no-wallet`
Install globally (after merging or pulling):
`npm install -g`
Launch wallet as separate server:
`$ hswallet --network=testnet`
Client commands work normally:
`$ hsw-cli --network=testnet send ts1qwdd3xdw54u2mfdnltz6lnt4vr8ks5lc3seexjc 0.1`

bin: allow wallet to run separately from node server

---

lib/primitives/txmeta.js
test/txmeta-test.js

Cherry-pick of https://github.com/bcoin-org/bcoin/pull/461
> 
> 
> Current behavior: the unconfirmed tx reports 505 confirmations, which is the current block height plus 2 (`chainheight - txheight + 1`) because `txheight` is `-1` when unconfirmed.
> 
> ```
> $ bwallet-cli send rb1qpymv5nnjcwngwpx93nvxm0wc7470nzu9rz2r99 0.01
> {
>   "hash": "0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005",
>   "height": -1,
>   "block": null,
> ...
> 
> $ bcoin-cli tx 0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005
> {
>   "hash": "0babb01107d616b27e1831877558e369b00dffd7827fdcd624b7b21434869005",
>   "witnessHash": "aec9b25b8f178ea4bd6b9811e02dbc775986a376b40986b85e1976ef6b25328c",
>   "fee": 2860,
>   "rate": 19861,
>   "mtime": 1526317134,
>   "height": -1,
> ...
> …
```

txmeta: fix confirmations calculation

---

lib/node/rpc.js
test/http-test.js
test/node-test.js

This PR updates the node RPC validateaddress to
better seperate the wallet and the node. The RPC
was returning ismine and iswatch only. These values
were moved to the wallet rpc method getaddressinfo.
This corresponds to a change in bitcoind and bcoin.
The updated validateaddress rpc returns the values:
- isvalid
- address
- ismine
- iswatchonly
- isscript
- isspendable
- witness_version
- witness_program
See PR in bcoin: https://github.com/bcoin-org/bcoin/pull/731
See PR in bitcoind: https://github.com/bitcoin/bitcoin/pull/10583

rpc: update node rpc validateaddress

---

lib/coins/coinentry.js

This commit just removes the index parameter from jsdoc as the function
no longer requires that parameter at all.

coinentry: remove unused parameter from JSDoc

---

lib/hsd.js

This commit simply adds the Covenant to the list of exports. It's a
primtive that I believe is used quite a bit by external developers, so
it would be very useful to have it exported easily rather than having
the developers manually point to the path, especially considering that
every other primitive that makes up a block -> transaction is exported.

exports: export Covenant along with other primitives

---

lib/node/rpc.js
lib/primitives/tx.js
lib/primitives/txmeta.js
test/txmeta-test.js

```
This commit adds the toString('hex') function to the following places:
- primitives -> txmeta -> getJSON()
- primitives -> tx -> format()
- node -> rpc -> getblockhash
In addition it adds a small test to txmeta-test to ensure that the getJSON function is working accordingly. 
```

various: convert buffer to string for JSON

---

test/contractstate-test.js

Adds tests for the ContractState class that is used
in the mempool to track the state of the chain along
with transactions in the mempool.
An instance of the ContractState class has a series
of maps for different types of name related outputs.
These tests create txs containing name related outputs
and assert that the ContractState indexes them
correctly based on their covenant type.

test: contractstate

---

Dockerfile

Recent versions of bcrypto have been linking to gmp.h which is causing
build issues inside of the alpine dockerfile.
This commit adds gmp-dev to the dependencies installed in the dockerfile
before npm install is called - allowing bcrypto to be compiled
successfully.

docker: add gmp-dev to fix compilation issues on Alpine

---

test/coin-test.js

This test shows that the coin is properly instantiated
for each network fromJSON and then can be written to
a buffer writer and then recovered from the buffer
writer with all of the same properties.

test: include coin serialization tests

---

lib/node/http.js
test/http-test.js

`GET /` will now return the chain tip's `treeRoot` property at `.chain.treeRoot`
Partially addresses https://github.com/handshake-org/hsd/issues/167

node/http: expose treeRoot of tip

---

lib/node/rpc.js

Add an additional field to the response of `getblockchaininfo` for the `treeRoot`
Partially addresses https://github.com/handshake-org/hsd/issues/167

node/rpc: add treeRoot to getblockchaininfo

---

README.md

Users are confused because the Proof of Work algorithm has
changed and hs-miner is no longer the best way to mine.
It was observed during testnet3 that hashrate for the hsd
miner was far greater than the hashrate for hs-miner. There
is also a bug in hs-miner regarding an incorrect header size.
This PR updates the README.md to only mention the hsd CPU miner.
Community members are working on a GPU miner that is not
out of beta yet.
See:
https://github.com/handshake-org/hs-miner/issues/12
https://handshake.community/t/error-bad-header-size-when-starting-miner/66

readme: update mining instructions

---

lib/wallet/node.js

The `witness` option in `lib/wallet/node.js` is left over from bcoin. This pull request deletes it because it is not used in the `walletdb`.

wallet: remove dead option

---

lib/primitives/mtx.js

Quick fix in the JSDoc, replaces the word `script` with `witness`

mtx: update addInput jsdoc

---

lib/wallet/txdb.js
test/wallet-test.js

Handle double spend with multiple inputs. Port of
https://github.com/bcoin-org/bcoin/commit/eba7bbeddc3f22c69ee249bb4f87e0dc9bec1bf9

wallet: handle multiple conflicting inputs

---

lib/node/http.js
test/http-test.js

Add an object for the db state at `.chain.state`
that has the fields `tx`, `coin`, `value`, `burned`.
These values are pulled from the `chain.db.state`.

node/http: add db state info to response

---

.circleci/config.yml

Currently we aren't able to run linting on Handshake without a globally
installed eslint. This will install bslint which should cover all of the
linting needs, as well as removes eslint install from the ci script.

lint: convert eslint to bslint for ci

---

lib/wallet/http.js

Add a `sign` parameter that defaults to true.
The created transaction will only be signed if
`sign` is true. This makes it much easier to
create transactions for wallets where the keys
are not stored on the server. The client can pass
`sign: false` and the request will return an
unsigned transaction that can be signed using
a hardware device.

wallet/http: allow creation of unsigned tx

---

lib/node/http.js

This commit simply adds an enforce line to check that the height being
requested to reset to is below the chain tip. This way we return a bad
request error rather than a internal server error.

http: add check for height being below tip

---

lib/wallet/wallet.js

There are many different types of transactions regarding the auction system. Each covenant type has its own explicit code path for creation. Currently, only the `send` functionality has a lock around it which means that there is *no* lock being used for code that wants to create the transaction but not sign and/or broadcast it. This pull request adds a new method for each create transaction type method that wraps the actual method with a lock.
Since there is no enforced concept of private methods in Javascript, this makes each of the create transaction methods safe for external consumption. These functions were only being called from within the wallet before, but in an attempt to better support watch only wallets, the create transaction methods would like to be consumed from outside of …

wallet: add locks for create code paths

---

lib/wallet/rpc.js
test/wallet-rpc-test.js

Adds a new wallet RPC method getaddressinfo that
corresponds to changes with bitcoind. Returns values:
- address
- ismine
- iswatchonly
- ischange
- isspendable
- isscript
- witness_version
- witness_program
The ismine property previously existed on the node RPC
method validateaddress which was always hardcoded to true.
An additional PR will be added to update validateaddress
to remove the ismine property. isspendable refers to
an address with null data, of version 31.
See PR in bcoin: https://github.com/bcoin-org/bcoin/pull/731
See bitcoind docs:
https://bitcoincore.org/en/doc/0.17.0/rpc/wallet/getaddressinfo/

rpc: new wallet rpc getaddressinfo

---

lib/net/common.js

This commit updates the documenation on two constants in the net common
file. The first is the required services which are now only NETWORK and
not NETWORK and SEGWIT. The second is an update to the maximum message
size. The max message size was updated from 4mb to 8mb in commit: 4c5668994162053be6c02d3af5c7959b6a572b47

net: jsdoc fixes for constants

---

README.md

People have been experiencing issues with the native code automatically compiling after running `npm install`. Adding a section about `node-gyp` will help to give people a path forwards when it doesn't compile correctly. An incorrect version of python was the most common issue that I have experienced when talking to people that want to run `hsd`, especially because newer distros have `python3` as the default `python`.

readme: add blurb about node-gyp

---

lib/wallet/http.js
test/wallet-http.js

This exposes the parameters `locktime` and `sort` through the REST API for the endpoint.
`locktime` will set the nLocktime field on the transaction and `sort` will sort the inputs/outputs using [bip 69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki)
- `POST /wallet/:id/send`
- `POST /wallet/:id/create`
It also includes tests

wallet: add locktime and sort params for HTTP send/create

---

lib/blockchain/chain.js

This is a quick PR to update the jsdoc to be specific to Handshake instead of leftovers from Bitcoin. The docstring mentions p2sh and segwit deployments, which are not relevant to Handshake. This changes the docstring to mention the hardening and the 2017 rollover instead.

jsdoc: update chain getDeployments

---

lib/net/framer.js

This commit fixes a small jsdoc param that is not longer used.

framer: fix jsdoc parameters

---

lib/node/http.js
test/http-test.js

This Pull Request adds 2 additional HTTP endpoints on the Node.
- `GET /mempool/invalid`
Returns the parameters of the mempool rejections bloom filter and the bloom filter itself if the query param `verbose` is sent. The bloom filter itself is very large.
- `GET /mempool/invalid/:hash`
Tests the hash for inclusion in the bloom filter.

mempool: expose mempool rejection filter to api

---

lib/net/netaddress.js
lib/net/peer.js
lib/node/http.js
lib/node/rpc.js

This PR implements the plumbing required to expose the identity key for both the node itself and its peers.
Changes:
- Add a `getKey` method to the `NetAddress`
- Add a `fullname` method to the `Peer`
- Add `.pool.identitykey` to  Node `GET /`
- Add `identitykey` to the response of Node `getnetworkinfo` RPC
- Return fullnames (key@ip:host) for Node `getpeerinfo` RPC
- Set the key on `Peer.local` so that it can be easily returned with `Peer.local.fullname()`, before it was not being set at all

rpc and http expose identity key

---

lib/script/common.js
lib/script/script.js
test/data/script-tests.json

Closes https://github.com/handshake-org/hsd/issues/224
Replaces https://github.com/handshake-org/hsd/pull/227
It seems this opcode may be more trouble than it is worth for Handshake. We already have a native covenant system, and a proposed consensus update to enable on-chain atomic name sales (https://github.com/handshake-org/hsd/pull/198).
This PR removes the opcode from the scripting system and adjusts tests that called it to throw the appropriate error (`BAD_OPCODE`)

[consensus] Script: remove OP_CHECKOUTPUT and OP_CHECKOUTPUTVERIFY

---

lib/primitives/tx.js
lib/script/common.js
test/sighash-test.js

Implement a new sighash type `SINGLEREVERSE`. This sighash type is similar to `SINGLE`, but is different because instead of committing to the same output index as the input's index being signed, it commits to the index at `(outputs.length-1) - index`.
If the first input was signed with `SINGLEREVERSE`, then it would only commit to the final output.
This is useful because covenants are "linked", so that the next covenant in the series must be at the same index as the input. This new sighash type allows a user to commit to the covenant input but not the output for that covenant.
This is a building block for atomic name swaps on chain.
An additional way to do this would be `SINGLENEXT`, where the `i + 1`'th output is committed to.

sighash `singlereverse`

---

lib/mining/cpuminer.js
lib/mining/mine.js
test/miner-test.js

This commit adds multiple tests to test the new proof of work function.
Mainly, mining a block is tested, as well as mining a block with a mask
that mimics what they would receive from a pool.
We also added in an extra parameter to the mine function to allow for a
nonce to be passed in instead of starting with 0. This should have zero
side effects as if it is not included, we default to the previous value
(0). We also add a funciton named mineRandomNonce that uses a random
nonce value to start iterating from - simulating a pool-like
environment.
Co-Authored-By: Mark Tyneway <mark@purse.io>
Co-Authored-By: Sean Kilgarriff <seanpkilgarriff@gmail.com>

test: add mining test for new proof of work

---

lib/covenants/index.js
lib/hsd-browser.js
lib/hsd.js

This is an update I needed to bundle `hsd` for the browser in my experimental hsd SPV browser node: https://github.com/pinheadmz/mobilehsd
From the global `hsd` object, for example, there is otherwise no method to get a namehash (sha3 digest of a rules-verified string). There's also no way to decode a `Resource` obtained via SPV `getProof` messaging.
I didn't think all the submodules were necessary, this is what is now exposed:
```
// Covenants
hsd.covenants = require('./covenants');
hsd.Namestate = require('./covenants/namestate');
hsd.Ownership = require('./covenants/ownership');
hsd.Rules = require('./covenants/rules');
// DNS
hsd.dns = require('./dns/server');
hsd.Resource = require('./dns/resource');
```
Note that `dns/server` exports two objects: 
```
exports.RootServer = …
```

hsd: expose covenants and dns in global hsd.js object

---

lib/dns/records.js

Fix TLSA record parsing so that they will be accepted and emitted by testnet4 resolvers.
(This change should eventually be merged into master as well)

dns/records: bugfix assertion in TLSA JSON parsing

---

Dockerfile

Without GMP in the base image, attempting to run the image leads to `Error loading shared library libgmp.so.10` which gets suppressed and reported confusingly as `Bindings for bcrypto were not built`

Dockerfile: gmp-dev is required by bcrypto at runtime

---

lib/dns/records.js

The `SMIME` record is defined to have a `certificate` but the `fromJSON` method looks for `fingerprint`. This PR renames `fingerprint` to `certificate`.

dns/records: fix smime parsing bug

---

lib/node/rpc.js

If the `name` isn't passed along to `resource.getJSON`, then the `name` will be `null` in the JSON.

rpc: getnameresource return name

---

lib/workers/worker.js

The workers will now have the title
`hsd-worker` when they run, instead
of the generic `node` title.
Port of bcoin commit:
ace4a08ebfbd4179c24b7c2fac49a68c52818372
Co-authored-by: Mark Tyneway <mark@purse.io>
Co-authored-by: Braydon Fuller <braydon@purse.io>

worker: use specific process title

---

lib/dns/records.js
lib/dns/resource.js

The Handshake `SSH` record type was defined to have a `keyType`, but the `bns` based `SSHFPRecord` was defined with a `digestType`.
This commit changes the `keyType` property to being called `digestType`, as the data was not being properly assigned in `hsd/lib/resource` when the `Resource` was being rendered into a `sshfp` DNS request.
Closes #285

dns/record: fix ssh record object property

---

lib/wallet/masterkey.js
lib/wallet/wallet.js

Basically, since `toJSON` was incorrectly used instead of `getJSON`, all keys were being serialized with the default mainnet prefix instead of the prefix corresponding to their actual network.

wallet: include network in master key JSON serialization calls

---

lib/dns/server.js

The `RecursiveServer` duplicates the logic for parsing `options.host`. This Pull Request eliminates the second time that it is parsed.

dns/server: remove duplicate opts parsing

---

lib/dns/server.js
lib/node/fullnode.js
lib/node/spvnode.js

This PR adds a new config option `rs-no-unbound` that is expected to be a boolean. If set to true, it will not use `unbound` and instead use the node.js based `RecursiveResolver`.
Since `initNode` sets listeners on `this.hns`, it is moved to after the call to `initOptions`, since `initOptions` can will overwrite `this.hns` if `noUnbound` is set to true.

dns/server: allow configurable use of unbound

---

test/auction-reorg-test.js

This PR simply updates the names of the `describe` blocks in `test/auction-reorg-test.js` so that they do not conflict with the `describe` blocks in `test/auction-test.js`. This prevents developer confusion when running tests, as the names of the `describe` blocks are printed to the console by the test runner. Developers will no longer potentially be thrown off and waste time looking in the wrong test file.
Note that no actual test functionality is modified, re:
```
// DO NOT TOUCH THESE TESTS
// They trigger the tree interval reorg bug.
```

test: rename reorg test describe blocks

---

lib/dns/resource.js

Resource.toA and toAAAA will also add
TXT records to the response. This will
authenticate the Onion and OnionNG records.
Addresses comment https://github.com/handshake-org/hsd/pull/265#discussion_r340285696

dns/resource: onion{ng} dnssec

---

lib/dns/records.js
lib/dns/resource.js
test/data/resources-v0.json
test/dns-test.js

This PR includes a test that purchases names and then writes one of each of the different Handshake records into the tree. A DNS stub resolver then queries for the name and asserts on the correct data being returned.
The DNSSEC test tests that all resource records sets in the answer and authority sections are signed. If all resource record sets in the additional section were signed as well, it could cause problems because there could potentially be many signatures and would force the DNS server to fall back to TCP. Ideally a different authentication mechanism is devised, because the DNSSEC key is public information anyways.
@boymanjor happy to split this up into smaller PRs if it would make it easier to review
Closes https://github.com/handshake-org/hsd/issues/264

test: add dns resolver tests

---

test/block-test.js

Cleans up `block-test.js` and ports the test from https://github.com/handshake-org/hsd/pull/249

test: block and memblock serialization

---

package-lock.json
package.json

Use a community managed [binet fork](https://github.com/Handshake-Protocol/binet) using a git repository similar to the proposed method in `bcoin` here: https://github.com/bcoin-org/bcoin/pull/910/
I am using a specific git hash instead of cutting a new release of binet because it is expected that more binet updates will be coming soon. We can cut a release when we have everything merged that we need.

testnet: use binet fork with fixes

---

lib/protocol/networks.js

The new magic is `taco`, h/t @pinheadmz 
This will prevent problems with peers trying to sync the previous simnet.

experimental-testnet: update magic

---

lib/wallet/wallet.js
test/wallet-http-test.js

This PR mitigates a bug which potentially stores an incorrect
account index in the db of watch only wallets. This is only a
patch of a specific API endpoint. It is necessary for recent
work on ledger-app-hns. Specifically, we have implemented
on-device output verification and need to be able to retrieve
a reliable path to verify and skip change outputs.
Future work involves fixing the source of this issue. For more
details see: https://github.com/bcoin-org/bcoin/issues/698.

wallet: mitigate watch only wallet bug for getKey

---

lib/dns/server.js

Adds a `lookup` method to the `RecursiveServer` that wraps `hns.lookup`. This makes it easy to hook into the `RecursiveServer` through alternative means, ie DNS over HTTP. This is a building block for a DNS over HTTPS proxy in front of `hsd`.
The `lookup` method accepts the name and RR type, which abstracts away the need to create a `Message`.
There is a `lookup` method passed to the `RootServer` that is responsible for looking up names in the authenticated tree. Now both servers have a `lookup` method.
https://github.com/chjj/bns/blob/f889a41234fc6ea53df8450970730a0af1b69dc0/lib/resolver/recursive.js#L577

dns/server: add lookup method to rs

---

lib/wallet/txdb.js
test/wallet-auction-test.js

Closes #53 
This PR solves the following issue:
1.  hs-wallet send open `name`
2. generate enough blocks to expire auction without a single bid
3. re-attempt: hs-wallet send open `name`
This currently throws the error `Already sent an open for: name`, but is otherwise allowed by the protocol.
What I did was add one more check to `wallet.makeOpen()` so it won't throw if the name is expired.
Also adds a new test module `wallet-test-auction` which is a sort of integration test, because it needs to test an actual `WalletDB` (not `memwallet`) with a `chain` and `miner`.

wallet: allow duplicate open after auction expires

---

lib/blockchain/chain.js

Fixes a typo in the `Chain` codepath that minimally verifies blocks that pass `isHistorical()` i.e. are below a checkpoint. This code can not be executed without checkpoints saved in `networks.js` and without setting the `checkpoints: true` option. So, not super urgent for a little while on main net.
Normally we check block headers with `block.checkBody()` as seen here, plus a lot more verification:
https://github.com/handshake-org/hsd/blob/c554a6fc15594024b96a4ddc544ff54a0a7cb4f1/lib/primitives/block.js#L237-L251
Below checkpoints, only the headers are checked so the code in `Chain.verify()` should be like the snippet above.
Will add checkpoint tests soon, but wanted to get this on the board ASAP in case a checkpoint is needed early on in main net.
The effect of this bug is that nodes …

bugfix: compute witnessRoot if a block is historical (below a checkpoint)

---

lib/blockchain/chain.js
lib/mempool/mempool.js
lib/node/spvnode.js
lib/protocol/network.js
lib/protocol/networks.js
test/disable-goosig-test.js

Edited 1/24/20
Adds a new hard coded deployment that disables GooSig after 1 year and 1 month of blocktime. This is to prevent the cryptography being broken in an unforseen way or a social attack where somebody claims it is broken when it actually isn't.
~~Two~~ One new field is added to `lib/protocol/networks`
- ~~`[network].airdrop.disableGoosig`~~
- ~~`[network].airdrop.disableGoosigHeight`~~
- `[network].goosigStop`
~~I used 2 variables to be very explicit, `disableGoosig` is a boolean and `disableGoosigHeight` is an integer. We could combine them into a single variable using `-1` as `disableGoosig: false` if that is preferred.~~
~~The `DeploymentState` is updated with a new property `goobye` and a getter `hasGooBye`. I wasn't sure what the best name for this deployment is, so I just …

chain: disable goosig after 1 year + 1 month

---

lib/blockchain/chain.js
lib/mempool/mempool.js
lib/protocol/network.js
lib/protocol/networks.js
lib/wallet/wallet.js
test/chain-test.js
test/mempool-test.js
test/txstart-test.js
test/wallet-test.js

Before headers-first sync is implemented, full nodes are vulnerable to disk-fill attacks. The simplest solution to this is to reject forks prior to the latest checkpoint. See: https://github.com/bcoin-org/bcoin/pull/764.
This could be especially problematic for a low-work chain without any checkpoints.
In order to build up a decent amount of chainwork and give the developers a chance to release a patch with at least one buried block checkpoint, we've discussed eliminating all transactions for the first two weeks of mainnet.
This PR adds the consensus rule that rejects transactions from the mempool and blockchain for the first 14 days worth of blocks. This also means the original value for `auctionStart` had to be bumped from 10 to 14 days. I set the ban score for relaying transactions to …

[consensus] No transactions for the first two weeks

---

lib/net/pool.js

After the recent standard + brontide update, the `Refilling peers` message was broken. Investigated and found one more usage where `peers.outbound` was being used. Fixed.

pool: fix refill peers

---

lib/net/peer.js
lib/net/pool.js

Refactor of `Pool.fillOutbound` and `Pool.addOutbound`. This duplicates the original logic for adding peers but now for both standard and brontide connections. The random element of sometimes not attempting to connect to brontide peers was removed, as the safety from not dos'ing yourself should come from a low outbound count, not waiting longer before trying to connect to peers. This way a node can quickly connect to another brontide based peer quickly if one drops, which is important for spv nodes doing name resolution. It is also important for nodes that only connect to brontide based peers.

pool: refactor fill outbound logic

---

lib/node/rpc.js

Previously this log statement would log a `Buffer`, but it should actually log a `string`. ~~This pull request switches the `block.hash` method to using the `block.toHex` method.~~ This pull request uses the correct string formatting symbol in the logger statement so that a string is logged instead of a stringified `Buffer`.

node/rpc: fix logger statement

---

etc/sample.conf
lib/net/peer.js
lib/net/pool.js
lib/net/slidingwindow.js
lib/node/fullnode.js
test/peering-test.js
test/slidingwindow-test.js

An alternative approach to solving the dynamic DOS prevention for `getproof` p2p messages, using the Sliding Window Counter algorithim:
https://blog.cloudflare.com/counting-things-a-lot-of-different-things/
https://github.com/RussellLuo/slidingwindow
It is much simpler to reason about because you only need to keep track of current and previous windows.
Assume that we need to limit to 100 requests per second, in the simplest case:
< 1s >
-------
| 100 |  
-------
all 100 requests fall in the same window, so no more can be allowed.
In the second case:
<1s> <0.5s>
------------
| 50 | 50 |
-----------
50 requests fall in the previous window, 50 in the first half of the current window (0.5s). Since the current window is not yet done, we need to appromixate a score with the current knowledge. …

getproof - dos prevention using sliding window counter

---

test/auction-rpc-test.js
test/wallet-http-test.js

Tests on circle ci were failing because of node client timeout as well as http test timeout. Fixed.

test: increase rpc, http timeouts

---

lib/mempool/mempool.js
test/mempool-test.js

Closes https://github.com/handshake-org/hsd/issues/306
Port of https://github.com/bcoin-org/bcoin/pull/917, although it hasn't been reviewed or merged yet over there. I think this is a bigger concern for Handshake since this codebase will represent 100% of the network, and chain reorgs are more likely on hsd in the early days.
The contextual checks for TXs with covenants re-entering mempool after a block disconnect has already been written in `_handleReorg()`, so for that case I just added a test.
The other cases ported over from bcoin are premature coinbase spends, and premature BIP68 sequence lock spends.
With these contextual checks in place, the "don't remove block if mempool empty" check can be safely removed.

Improve re-insertion of TXs from disconnected blocks into mempool

---

lib/net/slidingwindow.js
test/slidingwindow-test.js

The sliding window timer should be a `setInvterval` since it needs to `reset` _every_ second. There was only a unit test for this and unfortunately it was covering only the first `reset`.  Fixed and added a integration test. The current test sleeps for a second after 10 requests, giving the window enough time to `reset` and accommodate requests which are spaced out across multiple sliding windows.

peer: fix sliding window timer

---

lib/blockchain/chain.js

Sorry, the txStart rules I wrote will cause SPV node to throw 😬.
This won't matter after we cross the txStart threshold, and SPV nodes won't do much good until then anyway.
```
[debug] (net) Error: Cannot read property 'outputs' of undefined (165.22.151.242:12038)
at Chain.connect (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:2032:14)
at Chain._add (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:1972:30)
at async Chain.add (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:1900:14)
at async Pool._addBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:2409:15)
at async Pool._handleMerkleBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:2979:7)
at async Pool.handleMerkleBlock …
```

chain: don't check coinbase TX in SPV mode

---

lib/wallet/client.js

`wallet: fix ChainEntry parsing in remote wallet NodeClient`:
Without this patch, `hs-wallet` running in a separate process will not be able to `rescan`. As it receives `'block rescan'` events from the full node, it parses them incorrectly, thinking each blocks' height is wrong and cancelling the process. I think this may have been leftover from rearranging the block headers for the new proof-of-work.
`wallet: pass nameHash to getNameStatus in remote wallet NodeClient`:
Parameter was missing so trying to send a bid with remote wallet would throw an assertion error in `hs-client`:
https://github.com/pinheadmz/hs-client/blob/aa246e2f43c5ab8c3e4cf022c17e17dd4d7aa6e2/lib/node.js#L260
```js
getNameStatus(nameHash) {
assert(Buffer.isBuffer(nameHash));
return this.call('get name', nameHash);
} …
```

Fixes for running remote wallet server

---

lib/net/hostlist.js

Closes #359 
Fixes two bugs. It's a bit weird since how we manage getting hosts from a DNS seed is by adding a port to the seed. We won't use that port (DNS lookup ignores that port, and does it's DNS thing on port 53 anyway) but it is inherited by all the hosts we receive from the DNS seed, which are otherwise just IP addresses in A/AAAA records.
There is also I think some leftover code from before the Brontide refactor, where we would attach the ID key of the DNS seed to all the hosts we received as A/AAAA records. I'm not sure how that was supposed to work, but it seems cleaner now to set the key to `null`.
This fix will have to be upgraded in the future if we switch to `SRV` records like in [BOLT-10](https://github.com/lightningnetwork/lightning-rfc/blob/master/10-dns-bootstrap.md) …

Attach network default clearnet p2p port (and null ID key) to hosts received from DNS seeds.

---

lib/node/rpc.js

node RPC: fix logger format for block hashes

---

lib/blockchain/chain.js
lib/mempool/mempool.js
lib/mining/cpuminer.js
lib/mining/template.js

I was using the airdrop error messages for something and noticed a typo in one of the cases. When I went to fix it, I noticed a bunch of other "aidrop" typos. This PR fixes them all.
Edit: upon further review it seems this PR actually affects behavior.
The mempool defines a `Mempool.hasAirdrop` function but refers to it everywhere as `Mempool.hasAidrop`. This is only used in the `Mempool.limitSize` function which appears to guarantee the mempool does not exceed the max size. So it seems that if the mempool were to exceed the size limit, we'd get some sort of "`this.hasAidrop is not a function` error which would bubble up to unknown effect.

mempool: fix airdrop typo

---

lib/blockchain/chain.js
lib/node/rpc.js
test/bip9-chain-test.js

Port of https://github.com/bcoin-org/bcoin/pull/724
which is a port of bitcoin/bitcoin#9571
Test is ported from https://github.com/handshake-org/hsd/pull/332
adds a subsection to soft fork deployments indicating amount of miner signaling and a boolean if activation is "still possible" this period, given the signaling thus far and the time remaining in the window:
```
"statistics": {
"period": 2016,
"threshold": 1916,
"elapsed": 377,
"count": 290,
"possible": true
}
```

add BIP9 signaling statistics to rpc getblockchaininfo

---

lib/wallet/txdb.js
test/wallet-test.js

Closes https://github.com/handshake-org/hsd/issues/381
Replaces https://github.com/handshake-org/hsd/pull/385
Explanation here: https://github.com/handshake-org/hsd/issues/381#issuecomment-596240003
The test runs through the REVEAL of an auction two ways: First, by sending and then confirming each covenant. Second, by JUST confirming each covenant without first "sending". The difference from perspective of the txdb is that if a TX is not already inserted in an unconfirmed state, the balances will be wonky when the TX is confirmed.
Like #387 the patch is to first quickly update the "unconfirmed" data for a TX before proceeding (in the case where txdb sees a TX for the very first time, in a block)

wallet: update unconfirmed locked balance first during rescan

---

lib/wallet/txdb.js
test/wallet-test.js

This is a port of https://github.com/bcoin-org/bcoin/pull/829
Refer to original post for summary and discussion.
Note the hsd wallet has one extra detail in the `txdb.confirm()` function, it adds coins from the tx input to a `view`, which gets passed to `connectNames()` -- clearly not necessary in bcoin.
Since this PR only affects the handling of tx **_outputs_**, we should be ok. But reviewers more familiar with hsd might wanna double check me on that.
The reason we don't need to do anything for the inputs was discussed offline:
When txdb confirms a tx, it assumes that all input coins are confirmed. In fact, this is consensus for obvious reasons. If it sees an input it doesn't own, it ignores it. Even if the tx gets unconfirmed and re-confirmed, txdb will not recognize that credit or …

Create txdb credit for known key paths when confirming

---

.eslintfiles
README.md
bin/hsd-cli
bin/hsw-cli
package.json

This is a port of https://github.com/bcoin-org/bcoin/pull/707
After installation, links hsd-cli and hsw-cli directly to hs-client bin, already installed. 
Adds full deprecation message to `cli`.
This need was brought to my attention by a community post: https://handshake.community/t/help-chain-is-loading-mac-hsd/100
User seemed a little confused about CLI usage and I realized there is no explicit docs for CLI usage in HSD. (And actually in bcoin, it is a little [buried](https://github.com/bcoin-org/bcoin/blob/master/docs/cli.md) )

pkg: link hs-client to bin

---

bin/node
bin/spvnode
bin/wallet

Adds a listener in `bin/{node,spvnode,wallet}` on the `process` for `SIGINT` which then safely shuts down the node using `node.close`.
Port of https://github.com/bcoin-org/bcoin/commit/b18a8a3f13e147b607887b4adeadf49c8d7532fa.

bin: add sigint listener for safer shutdown

---

lib/wallet/wallet.js
test/wallet-test.js

port of https://github.com/bcoin-org/bcoin/pull/664
Just changing the error message to make more sense:
`No outputs available.` --> `At least one output required.`

wallet: better error for send() if no outputs given

---

README.md

Someone claiming their name was confused by the phrase "you must wait several blocks".  They thought claiming would take less than an hour. This copy is more clear.
For reference, the lockupPeriod is specified in networks.js:
https://github.com/handshake-org/hsd/blob/bbac8dd943767da62e46e52f93227b3da1048e17/lib/protocol/networks.js#L266

Specify the lockup period in README

---

lib/wallet/txdb.js
lib/wallet/wallet.js
test/wallet-accounts-auction-test.js

Closes https://github.com/handshake-org/hsd/issues/231
Adds new method hasCoinByAccount(acct, hash, index) to txdb which
returns true if the coin (hash, index) is owned by account (number).
Adds this check to wallet.makeReveal() to prevent BIDs from other
wallet accounts being included as inputs to a new REVEAL TX from a
specific account.
TODO:

wallet: accept account argument for all covenant makers and verify account ownership during coin selection

---

lib/blockchain/chain.js
lib/node/http.js
test/node-http-test.js

Emit an event over websockets for each time that a new tree root is set. 
The event is `tree commit` on the topic `chain`.
The event is added to `chain.setBestChain` which is called on every valid block that comes in. This means that this event could be triggered when a block that is not part of the best chain is received by the node.
Should we add additional information regarding if it is part of the best chain?
Or only make it so that the event is triggered when its part of the main chain?

node: event tree commit

---

lib/wallet/account.js

change address will not be saved if call hsw-cli change

wallet: fix change lookahed address

---

lib/node/rpc.js
test/node-rpc-test.js

Update the node RPC methods `getblock` and `getblockheader` for returning the `confirmations` as `-1` if the block is not in the main chain. There is no way to tell if a block is not in the main chain from the API without these changes.
Closes https://github.com/handshake-org/hsd/issues/312
Port of:
- https://github.com/bcoin-org/bcoin/commit/b9ad073b9bca527b0e6faca8a9f1781d7c68d175
- https://github.com/bcoin-org/bcoin/commit/54b31293ced0f3652651156ea5b285619371ef17
- Additional tests in `test/node-rpc-test` for `signmessagewithprivkey` and `verifymessage`
These changes have already been merged into `bcoin`

node/rpc: getblock confirmation fixes

---

lib/node/spvnode.js
lib/wallet/http.js
lib/wallet/node.js
lib/wallet/nodeclient.js
lib/wallet/plugin.js
lib/wallet/walletdb.js
test/wallet-test.js

This is an update and rebase of #333 ...
---
This is a port of the following bcoin PRs:
https://github.com/bcoin-org/bcoin/pull/931 wallet: set tip after txs have been added
https://github.com/bcoin-org/bcoin/pull/932 Prevent out-of-memory crash during sync with wallet as plugin 
https://github.com/bcoin-org/bcoin/pull/934 wallet: remove checkpoints that skip transactions
https://github.com/bcoin-org/bcoin/pull/939  fixes a bug introduced in https://github.com/bcoin-org/bcoin/pull/931
and also I applied:
https://github.com/handshake-org/hsd/pull/181 wallet: remove dead option
to one other place (`lib/wallet/plugin.js').
What we're doing here is removing dead code, keeping walletDB in sync with the chain without filling up memory, and preventing possible walletDB corruption after a crash.

wallet: port various fixes and improvements from bcoin

---

CHANGELOG.md
lib/wallet/rpc.js
lib/wallet/txdb.js
lib/wallet/wallet.js
test/wallet-importname-test.js

This enables a user to import a name into their wallet in a similar way to importing an address or public key. A rescan is still required to recover any auction activity and in particular the OPEN for a name MUST be rescanned or the wallet will not record a `nameState` or track any bids.
The WalletDB global `name->wid` map is used as a "watch" marker to determine if a name's OPEN should be added to the txdb.
The new rpc command takes a rescan height parameter:
```
hsw-rpc importname sad 2016
```
Wallet applications should check the state of a name and use a name's `height - 1` as the rescan height. Assuming the auction is still in bidding phase, this will initiate a wallet rescan of maximum 5 days.
See https://github.com/kyokan/bob-wallet/issues/108

Wallet: enable importing names and "watch" for auction activity without bidding

---

lib/dns/resource.js
lib/node/rpc.js
test/node-rpc-test.js

This PR adds a new Node RPC method called `validateresource`. It is useful for users who are in the process of creating their resource JSON to use with `sendupdate`. This PR adds error messages in the `fromJSON` methods of each of the records found in `lib/dns/resource.js`.
The RPC accepts a single object with the `records` property, which must be an array of objects.
Eventually, it could also accept a `version` property if another Resource version is implemented.
The error messages note the invalid JSON property name and the record type. This is so that good error messages can be returned to users. The error messages could be made generic (not including the record type in the error message) but that would mean that the RPC method handler itself would have to hold logic similar to …

node rpc: validateresource

---

lib/node/rpc.js

This feels like it should belong here, as I don't know if there is any other way to query the extra_nonce from blocks.

rpc: add extra_nonce to block's JSON.

---

lib/wallet/rpc.js

There was a missing space in the wallet RPC error messages for `sendupdate`, `createupdate`, `sendtransfer` and `createtransfer`. This PR adds in the space so that the error message renders correctly.

wallet/rpc: fix error message typos

---

lib/node/http.js
test/http-test.js

It can be useful to query for block headers directly without needing to query for full blocks.
Less disk i/o and less bandwidth would be needed when querying for just the block header.
It will also work for nodes in SPV mode.
This is a port of a PR to bcoin here https://github.com/bcoin-org/bcoin/pull/808/files

node/http: get header by hash/height

---

lib/wallet/wallet.js

The typical code path for generating covenants, specifically
bids, is through the createBid function. This function does
not check the output values against the wallet's dust policy
level. The createTX function should follow similar behaviour.
This check was previously added at commit 0bcc6af. This commit
removes it.

wallet: do check covenants for dust in createTX.

---

lib/wallet/txdb.js
test/wallet-test.js

There is currently a bug in the wallet where it assumes that `REGISTER` outputs only come from `REVEAL` outputs. This prevents any name claim from ever updating their name using the wallet API. It is still possible to manually create the `REGISTER` transaction and broadcast it directly to the blockchain without using the wallet API. This is risky because a user could forget to create the transaction with the additional output containing the value "locked in the claim" to themselves.
https://github.com/handshake-org/hsd/blob/4178fd3c86612e939e554a72f9e4aa85a55a9c37/lib/wallet/txdb.js#L1703-L1710
`REGISTER` outputs can also come from `CLAIM` outputs when the name is reserved.
https://github.com/handshake-org/hsd/blob/4178fd3c86612e939e554a72f9e4aa85a55a9c37/lib/covenants/rules.js#L1218-L1227 …

wallet: allow updating of claimed names

---

lib/wallet/http.js
test/wallet-http-test.js

Bids and Lockups are allowed to have value of 0, but get rejected by wallet http, which interprets the values as `false` and throws a "missing bid" error.
Also fixes `assert.reject` statements in wallet-http-test.js that weren't actually testing for the correct error message or executing asynchronously.

Allow bid and lockup with 0 value in wallet-http

---

lib/node/rpc.js

Add a `getdnssecproof` RPC method that accepts three arguments (two of which are optional), a domain name, an estimate `boolean` and a verbose `boolean`. Setting `estimate` to false will cause an error if the full proof cannot be made. Setting `verbose` to `false` will result in raw hex being returned, otherwise JSON is returned. This follows the same pattern as in the `bitcoind` RPC, see `getblock`.
This method uses the built in DNS resolver to query out to 8.8.8.8 or 8.8.4.4 and builds a DNSSEC proof.
Try it against any of the names in `lib/dns/tld.json`.
For example:
```$
$ ./bin/cli rpc getdnssecproof brave.com
```

node/rpc: getdnssecproof

---

lib/node/rpc.js
test/node-test.js

The `address` field in some of the Node RPC methods returns an object with a version and a hash. This pull request adds an additional field to that object called `string`, which returns the bech32 encoded address to make it easier for users that don't want to encode the object client side.
Closes https://github.com/handshake-org/hsd/issues/442

node/rpc: addrToJSON include bech32 string

---

lib/blockchain/chaindb.js

`getCoinsByAddress` currently expects an `Address` instance. I need to query for an address balance, from a plugin which receives a string input. I cannot cast the string to `Address` since they are from different modules. It would be nice to loosen the interface here to accept a string so that plugins can fetch coins by passing a string.
Otherwise, maybe we could add a RPC endpoint which accepts a string. I am currently using the HTTP API endpoint `/coin/address/:address` from the plugin.

chaindb: getcoinsbyaddress - handle string addrs

---

lib/dns/resource.js
lib/dns/server.js
test/ns-test.js
test/resource-test.js

SYNTH4 and SYNTH6 records are very special: they act like NS records that contain their own IP addresses, encoded in base32. They can therefore be resolved without any lookup whatsoever. It's a neat trick to save blockchain space and avoid using useless NS+glue.
This PR fixes three bugs in the hsd RootServer resolution of these records:
The server does not currently map IPv4 to IPv6 addresses before proceeding with response.
Without patch:
```
$  dig @127.0.0.1 -p 25349 _fs0000g._synth.
[error] (ns) Assertion failed.
at Object.isMapped (/Users/matthewzipkin/Desktop/work/hsd/node_modules/binet/lib/ip.js:734:3)
at Object.isIPv4 (/Users/matthewzipkin/Desktop/work/hsd/node_modules/binet/lib/ip.js:745:16)
at RootServer.response (/Users/matthewzipkin/Desktop/work/hsd/lib/dns/server.js:303:14) …
```

Fix RootServer resolution of SYNTH and GLUE records

---

CHANGELOG.md

Closes https://github.com/handshake-org/hsd/issues/446
(Did I miss anything?)
I think going forward, we should be vigilant about asking contributors to add details to CHANGELOG when necessary. I think little bug fixes (like allow bids of `0` value, etc) can be ignored. But definitely API changes should be recorded.

Update CHANGELOG with recent significant changes

---

CHANGELOG.md
lib/dns/server.js
lib/node/rpc.js

When playing with my node, I found that resetting the root cache was sometimes helpful. This adds a node RPC method called `resetrootcache` and it drops the root server cache completely. It would also be technically possible to expose deleting a single name (or a set of names) out of the cache.
DNS servers employ [Dynamic DNS](https://en.wikipedia.org/wiki/Dynamic_DNS) to allow for remote clients to configure the zone, so maybe it makes sense to have expose an RPC interface for the DNS servers. This would give users a more familiar interface for the configuration.
Or maybe restarting the node to clear the cache is good enough.

rpc: resetrootcache

---

lib/wallet/wallet.js
test/wallet-auction-test.js
test/wallet-http-test.js

Closes https://github.com/handshake-org/hsd/issues/463 maybe a few more...
These sanity checks are already applied to regular money-sending `NONE`-covenant transactions in the [`createTX()` method](https://github.com/handshake-org/hsd/blob/a3049d5b7e7feb431419e3c4d092bb71e17c86fc/lib/wallet/wallet.js#L3276-L3306)
However there is nothing yet to prevent a user from sending a BID with a lockup value that is below the dust threshold.
This is another issue with my least favorite line in the codebase, the "broadcast anyway" clause:
https://github.com/handshake-org/hsd/blob/a3049d5b7e7feb431419e3c4d092bb71e17c86fc/lib/node/fullnode.js#L335-L342
As much as I want to change the "broadcast anyway" behavior we still need the extra sanity check in the wallet for SPV nodes, which can't check new TXs …

wallet: check auction TXs for dust and null address before sending

---

lib/net/brontide.js

According to [LND brontide package](https://github.com/lightningnetwork/lnd/blob/master/brontide/noise.go#L451), ECDH operation at genActOne returns `es`.

brontide: fix typo in comments

---

.github/workflows/node.js.yml
CONTRIBUTING.md
README.md
package.json

Closes https://github.com/handshake-org/hsd/issues/489
Removes bslint from dependencies and installs it manually in workflows process for CI testing.
Added a CONTIRBUTING.md guide to explain how to install and use bslint since it is not automatic anymore. While there, added sections about bmocha and commit message preferences.
Linked that from README and, while there, removed the short list of RPC commands that we don't maintain and just linked to the API docs.

Remove bslint as dep. Install manually in workflows. Explain process in new CONTRIBUTING guide

---

test/script-introspection-test.js

Increase test coverage of `Script` module with the new handshake opcodes `OP_CHECKOUTPUT` and `OP_TYPE`.
These unit tests could be the basis for an integration test or separate application that uses hot/cold keys to build the update/transfer name-ownership script described in the whitepaper.

test: opcodes that introspect tx outputs

---

lib/primitives/address.js
test/address-test.js

Fixes a bug in `Address.isUnknown()` that mis-identifies nulldata addresses as non-standard and mis-identifies all other witness program versions as standard (version 0 addresses are obviously OK)
Note that Bitcoin Core has allowed more flexibility in relaying unknown witness versions: https://github.com/bitcoin/bitcoin/pull/15846 But I don't think we need to worry about that yet.
Unfortunately before nulldata addresses can be used for practical purposes like [provably prunable outputs](https://github.com/handshake-org/hsd/issues/481#issuecomment-664658894), this patch needs to be released and widely deployed, especially to miners.

[POLICY] address: fix isUnknown() to allow nullData and version 0 addresses

---

CHANGELOG.md
lib/wallet/layout.js
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/wallet-change-test.js

wallet: add migration to regenerate missing change addresses (WIP)

---

CHANGELOG.md
lib/wallet/txdb.js
test/wallet-test.js

I think we may have overlooked the impact of FINALIZE covenants on locked coins balances in the wallet. They are unusual because it is the only case where locked coins _leave the wallet_. Meaning someone else's locked coin balance goes up. The current txdb functions `lockBalances()` and `unlockBalances()` process covenants received into the wallet, however in this case we must also catch FINALIZE as it is being _sent_, since our own locked coin balance goes down (along with the total balance - name and coins get transferred) 
TODO:
- Evaluate the impact of this change on exiting wallets in use. Do we need another wallet DB migration?
- Will some users have to completely restore wallet from seed and rescan like the [claim-to-register issue?](https://github.com/handshake-org/hsd/issues/454) …

Adjust txdb locked coins balance for FINALIZE covenants

---

CHANGELOG.md
lib/node/fullnode.js
lib/protocol/policy.js
test/miner-test.js

Addresses https://github.com/handshake-org/hsd/issues/430 -- [solution 1 & 2](https://github.com/handshake-org/hsd/issues/430#issuecomment-614611881)
(see also #515)
Prevent low- or no-fee transactions from being stuck in the mempool forever, by adjusting mining policy to occasionally include them.
This PR is mainly changing a constant in policy.js from a value that used to be `0`:
```
/**
* Minimum block size to create. Block will be
* filled with free transactions until block
* reaches this weight.
* @const {Number}
* @default
*/
exports.MIN_BLOCK_WEIGHT = 5000;
```
What this means is, in miner.js `assemble()` when a block is being put together to be hashed, if the current block template has a total weight under 5000, the miner will insert "free" transactions from the mempool (very low …

Mining: set minimum block weight to 5000, parse as configuration option

---

lib/wallet/txdb.js
test/wallet-test.js

This is an edge case we should have addressed in #464 especially after dealing with basically the same behavior in #387. And actually if I'd written better test coverage in #387 to actually include TRANSFER and FINALIZE, we probably would've fixed all the bugs six months ago 🤷‍♂️ 😬 
The issue is that in bcoin and hsd, `unconfirmed` includes all confirmed amounts in addition to unconfirmed amounts, they are not mutually exclusive. Normally when we send a TX, it is inserted into the database as unconfirmed. Then when we see it in a block, we update the confirmed balance but we leave the unconfirmed balance alone (it was already updated when the TX was first seen in the mempool).
During a rescan (or more explicitly, an import-from-seed or [deep …

txdb: fix lockedUnconfirmed if FINALIZE is inserted with block

---

test/interactive-swap-test.js

This test isn't designed intentionally to increase test coverage but more to document one method of atomically swapping HNS coins for a name by using an interactive protocol and partially-signed transactions. We don't need to merge it but it may prevent some edge case regression in the future.
The flow goes like this:
- Alice owns a name and agrees to sell it to Bob for a certain price (they communicate any way possible, not on-chain)
- Bob sends Alice an address to receive the name
- Alice signs and broadcasts a TRANSFER covenant committing to Bob's address
- at this point, Alice still unilaterally owns the name.
- Bob can see the TX on the blockchain (so can everyone) and confirm his address is in the covenant
- at any time before the FINALIZE is broadcast, Alice can CANCEL the …

test: demonstrate interactive name swaps

---

lib/wallet/http.js
test/wallet-http-test.js

Fix the return of POST /reveal and /redeem when no name provided.

wallet: fix the return of POST /reveal and /redeem

---

test/mempool-test.js

This is the correct approach to fixing this issue, replacing https://github.com/handshake-org/hsd/pull/518 which still left us with [non-deterministic outcomes](https://github.com/handshake-org/hsd/pull/515/checks?check_run_id=1658641520).
I realized the problem is that the test called `fakeClaim()` TWICE, meaning the stub resolver actually requests cloudflare's DNSSEC chain twice from the actual legacy DNS. The non-determinism is a result of the stub resolver getting a slightly different result the second time, in particular the RRSIG over the TXT RRs in the final zone. Likely there are many redundant resolvers caching cloudflare.com's TXT RRs and the second `fakeClaim()` call sometimes ended up getting a slightly _newer_ signature, meaning its `inception` value exceeded the current …

Fix non-deterministic mempool reorg test

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/walletdb.js
test/wallet-deepclean-test.js

Closes https://github.com/handshake-org/hsd/issues/467
~Requires https://github.com/handshake-org/hsd/pull/512 (CI tests will fail until rebase)~ ✅ 
This will likely be required for users with walletDB corruption due to the `CLAIM->REGISTER` bug (https://github.com/handshake-org/hsd/issues/454) and/or the `FINALIZE` bug (https://github.com/handshake-org/hsd/pull/464)
walletDB deepClean():
- deletes all mapping of blocks, outpoints and tx hashes to wallet ids
- deletes (almost) the entire txdb (all history, all balance data, for all wallets)
- keeps all BID blinds (otherwise a human must remember the hidden values)
- keeps all account metadata (account name, type, address depth, etc)
- keeps all name->wallet ID mapping (although this may be unnecessary)
- keeps all address-hash path …

wallet: deep clean

---

CHANGELOG.md
lib/mempool/mempool.js
lib/node/fullnode.js
test/mempool-test.js

Port of https://github.com/bcoin-org/bcoin/pull/997 with explanation [here](https://github.com/bcoin-org/bcoin/issues/996)
(see also #514 )
Addresses https://github.com/handshake-org/hsd/issues/430 -- [solution 4](https://github.com/handshake-org/hsd/issues/430#issuecomment-614611881)
Summary: We already have logic to remove ["old"](https://github.com/handshake-org/hsd/blob/7826128ff72c20fdf42c659309dcffea7a28f6cc/lib/protocol/policy.js#L116-L123) transactions from the mempool, but that logic is never executed unless the mempool is full. This PR checks for and evicts old transactions every time a new transaction is added to the mempool.

Mempool: evict expired transactions regardless of current mempool size

---

test/wallet-http-test.js

Also removed `assert.ok(false)` in these handlers since those
assertion errors would be swallowed by the mempool event
emitter and would not be caught by the test suite anyway.
These test modifications can be tested themselves by reviewers
by setting `broadcast: true` inside `wallet.createOpen(...)`
ping @TLD-O I think this will help you add tests in #529

test: isolate mempool event listeners in wallet-http-test

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/wallet.js
test/wallet-http-test.js
test/wallet-test.js

At the moment, if I bid on a name now, I can't create the reveal and redeem transactions before the the name gets respectively in the reveal period and close period. That is, unless I use a web wallet (Namebase for example), I have get back X blocks later to create the reveal (and send it) and get back again Y blocks later for the redeem (and send it). I think we can keep the REGISTER out of the scope. 
The goal of this PR is to add the possibility to somewhat automate the auction process. The user will still have to either keep a personal hsd open to send the transactions at the right time or trust someone else to do it (sometimes referred as a kind of watchtower).
If it is accepted, a user could create a bid (and broadcast it immediately or not), and prepare the corresponding reveal and …

Proposal : add the possibility to create auction-related transactions in advance

---

CHANGELOG.md
lib/covenants/namestate.js
test/auction-test.js

Closes https://github.com/handshake-org/hsd/issues/178
example output:
```
$ hsd-rpc getnameinfo test-ds
{
"start": {
"reserved": false,
"week": 28,
"start": 56
},
"info": {
"name": "test-ds",
"nameHash": "c3243b05628fe67bde09bf7bf53752cd446fab5e0434d15c9d04c5db8dcb7ce4",
"state": "CLOSED",
"height": 211,
"renewal": 235,
"owner": {
"hash": "5c8beb5651b28c05c10133771933e42fea09130c983ebd27715b414ba30db757",
"index": 0
},
"value": 0,
"highest": 0,
"data": "0000e00b08022095a57c3bab7849dbcddf7c72ada71a88146b141110318ca5be672057e865c3e2",
"transfer": 245,
"revoked": 0,
"claimed": 0,
"renewals": 0,
"registered": true,
"expired": false,
"weak": false,
"stats": {
"renewalPeriodStart": 235,
"renewalPeriodEnd": 5235,
"blocksUntilExpire": 4990,
"daysUntilExpire": 34.65,
"transferLockupStart": 245, …
```

namestate: expose transfer lockup period

---

lib/wallet/path.js

JSDoc is complaining about a few optional parameters. 
[Optional parameters](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values) should be placed between `[square bracket]` instead of prefixed with `?`

Fix jsdocs

---

lib/protocol/networks.js

Reduces console spam when only a single node is running on regtest/simnet networks.
This was merged into bcoin (https://github.com/bcoin-org/bcoin/pull/694) and later into hsd (https://github.com/handshake-org/hsd/commit/eaf53f4f75eee45aee1208bdd9a554a606c40724, https://github.com/handshake-org/hsd/pull/106), but reverted by @chjj in https://github.com/handshake-org/hsd/commit/41558d8b698455a1e189d75191ffd2568fc56ae7 and https://github.com/handshake-org/hsd/commit/a2e357d9b57884a78bd7e406e3c7c98cc3deaf4b.
Is there any reason these must be hardcoded? They can always be added with arguments/config when required.

protocol: clear regtest and simnet seeds

---

CHANGELOG.md
lib/primitives/address.js
lib/wallet/txdb.js
test/wallet-rescan-test.js

Closes https://github.com/handshake-org/hsd/issues/510
This PR fixes a wallet issue that throws an assertion error during a rescan in a shockingly simple scenario:
- Alice OPENs a name. It doesn't matter if she bids or not
- Bob wins the name
- Bob sends a TRANSFER for the name. It doesn't matter if it's ever FINALIZEd or what address the TRANSFER commits to
- Alice rescans --> `assertion error  at TXDB.connectNames`
There are other related scenarios where Alice doesn't send the OPEN but does bid, and still loses. The crux of the issue has to do with UNDO DATA. Blockchain is generally designed to be append-only and therefore only move forwards. However there are scenarios in which the chain is rewound: a reorganization or a wallet rescan. In these scenarios, the software depends on UNDO …

wallet: save and recover undo data from critical namestate transitions

---

CHANGELOG.md
lib/dns/resource.js
lib/dns/server.js
test/resource-test.js

Closes https://github.com/handshake-org/hsd/issues/565
Based on https://github.com/james-stevens/hsd/commit/18cdabc43d79f88617e52aa56b18239e73a10709
TODO:
Changes:
- Root always signs DS, never signs NS, and only signs TXT _if NS is not present_
- Root always sets `aa` (authority) bit for DS, never for NS, and for TXT only _if NS is not present_
- Root doesn't answer a query for TXT if NS is present (sends referral instead)
- Root sets authority bit for NXDOMAIN

dns: fix root zone dnssec

---

test/anyone-can-renew-test.js

This PR just adds a test to hsd, but like #500 it also acts like a standardizing document for wallet implementations to use and most importantly, proves that the following addresses encode the following script hash. [Note that `8` is the type for RENEW](https://github.com/handshake-org/hsd/blob/a94ce87a886e943a68d4a3e67068f6e473c21156/lib/covenants/rules.js#L52)
```
Script: OP_TYPE OP_8 OP_EQUAL
Serialized script: d05887
Script hash: e466310e566f8f14ac36f7eb7607a5d77a2351ad6bb5aba20a17396c5b18b8c1
main:    hs1qu3nrzrjkd783ftpk7l4hvpa96aazx5dddw66hgs2zuukckcchrqsw3f8kc
testnet: ts1qu3nrzrjkd783ftpk7l4hvpa96aazx5dddw66hgs2zuukckcchrqsj8gmfv
regtest: rs1qu3nrzrjkd783ftpk7l4hvpa96aazx5dddw66hgs2zuukckcchrqs570axm
simnet:  ss1qu3nrzrjkd783ftpk7l4hvpa96aazx5dddw66hgs2zuukckcchrqs4kzusf
```
If …

test: provably locked anyone-can-renew/renew-only addresses for names

---

lib/dns/server.js
lib/node/node.js
test/ns-test.js

Closes #541
TODO: Include example plugins to close...

Make Root nameserver more flexible for plugins

---

.github/workflows/docs.yml

This is similar to the work done for https://hsd-dev.org/ in handshake-org/handshake-org.github.io/issues/102.
If this PR is merged, each release of hsd will update https://hsd-dev.org/hsd (not existing right now).
Next, we need to update `/docs` => `/hsd`
https://github.com/handshake-org/handshake-org.github.io/blob/a60e4b1b60334bcd38b215ebfcb3a50ae634e970/src/templates/layout.html#L44

Build docs to gh-pages

---

CHANGELOG.md
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/walletdb.js

Closes https://github.com/handshake-org/hsd/issues/563
This probably should have been included in https://github.com/handshake-org/hsd/pull/506
This PR adds an extra wallet option to upgrade wallets created before #506 was merged, that still have a lookahead of `10`. When the option is set, all accounts of all wallets are called with `Account.setLookahead(Account.MAX_LOOKAHEAD
)` which is now `200`. This will set the metadata lookahead value, generate whatever keys/addresses are necessary and write to the database. This only needs to be run once per walletDB, since the update is permanent.
Usage:
`hsd --wallet-check-lookahead`
Log messages:
```
[warning] (wallet) Setting lookahead for wallet primary account 0
[warning] (wallet) Setting lookahead for wallet ten account 0
```
Can be …

wallet: --check-lookahead to update old wallets

---

lib/dns/server.js

Making the request info available to plugins can be very useful. For example, to do access control based on IP address (bind has this feature). Also, Implementing some advanced features in DNS that requires knowing the protocol, port and IP address like the [HSD AXFR plugin](https://github.com/buffrr/hsd-axfr) which needs rinfo to send multiple dns messages over TCP.

dns: make request info available to plugins

---

CHANGELOG.md
lib/node/fullnode.js
lib/node/spvnode.js
test/dns-test.js

Closes https://github.com/handshake-org/hsd/issues/528
Summary (also included in CHANGELOG):
- `FullNode` and `SPVNode` accept configuration parameter `--no-dns` (or `no-dns: true` in
`hsd.conf`) which launches the node without either DNS server (the root authoritative
server and the recursive resolver). This avoids some port collisions with other HNS resolvers
like hnsd running locally, and generally separates and reduces security concerns around
running unneeded servers when a node is just used for transactions and blocks.
`--no-rs` is also accepted to disable the recursive DNS resolver (but keep the root server).
The default is `false` (meaning by default, hsd runs with the DNS servers).

node: accept --no-dns configuration option to disable NS and RS

---

lib/blockchain/chain.js
lib/mining/template.js
lib/node/rpc.js
test/getwork-test.js
test/node-test.js

It appears some (if not most) miners are using `getwork`/`submitwork` instead of `getblocktemplate`. This is presumably because `getwork` is just easier: it requires minimal implementation and serialization on the part of the mining software. `getwork` was originally only included for testing immature mining clients, however, the community's reliance on it requires us to give it a second look.
There is a nasty bug present in `getwork` which causes blocks to be invalidated when transactions enter the mempool. It seems that miners have been patching this bug themselves to avoid mining invalid blocks. I figure we should make an official fix asap.
This PR fixes `getwork` to allow operation on stale blocks with older merkle roots. 
Some things are also simplified: the RPC no longer …

Major fixes & improvements for getwork

---

CHANGELOG.md
lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/covenants/rules.js
lib/mempool/mempool.js
lib/mining/miner.js
lib/mining/template.js
lib/net/pool.js
lib/node/rpc.js
lib/protocol/network.js
lib/protocol/networks.js
test/auction-test.js
test/invalid-reorg-test.js
test/util/memwallet.js

On March 24th, @pinheadmz discovered an inflation bug pertaining to replacement name claims. Other Handshake contributors were notified and action was quickly taken to deploy a covert soft-fork in collaboration with various miners. As of this moment, ~90% of the network hashrate is signaling the covert soft-fork, and we have confirmation that at least 93% of the network hashrate is _enforcing_ the soft-fork (but perhaps not signaling).
Chain analysis reveals that __this bug has never been exploited on mainnet__, and is now impossible to exploit given the hashrate enforcing this change.
The inflation bug could be exploited as follows:
1. Create a claim for a reserved name with a chosen fee.
2. Create a replacement claim with another fee.
3. Step 2 can now be repeated infinitely.
_All_ fees …

Inflation bug fix (covert->overt soft-fork)

---

lib/types.js
lib/ui/amount.js
test/utils-test.js

Added small test vector.
Updated!
So changes:
- Removed toBits/fromBits.
- Apparently `uhns` was broken, it should be same as `doo`.
- Added `handshake` as amount unit type as well.
Notes about types:
- Added `@typedef` for unit enum: `AmountUnitType`
So we get currencies:
| Unit   | Decimal (HNS) | Exponent | Note              |
| ---    | ---           | ---      | ---               |
| `doo`  | 0.000001      | 0        | Base unit         |
| `uhns` | 0.000001      | 0        | micro-hns or μhns |
| `mhns` | 0.001         | 3        | milli-hns or mhns |
| `hns`  | 1             | 6        | or `handshake`    |
There's an issue with conflicting types: `lib/types` defines global typedefs for the project.
There's typedef: https://github.com/handshake-org/hsd/blob/2d1cbe9c17b0ad4e8858c06a8 …

utils: fix amount to unit.

---

README.md

The git URI scheme usually implies the unsecured native Git protocol
which is vulnerable to man-in-the-middle attacks. Using TLS based HTTP
should be an obvious security improvement.

Update documented reference for Git clone to https: URI.

---

lib/node/rpc.js

For mining pool development, I think it would be more convenient to have FEE as one of the results returned by getWork.

[getwork-RPC] Add the fee to the return result of getwork.

---

lib/wallet/http.js

This swaps 2 lines in wallet/http for `deepclean`, so the HTTP response does not return until walletDB is done with deep clean. It should be a relatively fast operation for most wallets (it doesn't have a built-in rescan any more). Worst case is the http request times out, but I think thats preferable to no one ever knowing when deep clean is done.

wallet-http: do not return until deepclean is done

---

lib/node/rpc.js
lib/wallet/rpc.js
test/wallet-rpc-test.js

#606 item 2: Create new RPCs `signmessagewithname` and `verifymessagewithname`

Sign & verify message with name

---

CHANGELOG.md
lib/wallet/rpc.js
test/wallet-rpc-test.js

#606 item 1: signmessage should only work for public-key-hash addresses.
Note: I'm reusing the `INVALID_ADDRESS_OR_KEY`, not sure if it would be better to have its own error code.

signmessage rejects multisig wallet

---

lib/wallet/http.js
lib/wallet/rpc.js
test/wallet-http-test.js
test/wallet-rpc-test.js

Closes https://github.com/handshake-org/hsd/issues/586
When a user tries to redeem multiple losing bids for multiple names by calling `sendRedeem` with `name: null`, the http module calls a specific function `sendRedeemAll()`. This function was not getting passed the wallet passphrase, and so encrypted wallets would always fail. 
This PR simply passes the passphrase (and the rest of the TX options like `subtractFee`, etc) to that function.

wallet: pass passphrase + TX options to sendRedeemAll())

---

CHANGELOG.md
lib/wallet/rpc.js
test/auction-rpc-test.js

Sumamry (added to CHANGELOG):
`rpc getbids` accepts a third parameter `unrevealed` _(bool)_ which filters the response by checking
the wallet's unspent coins database for each bid. If an unspent coin is found, the output address
of that coin is added to the JSON response. This is useful for wallet recovery scenarios
when users need to call `rpc importnonce` to repair unknown blinds. The complete usage is now
`rpc getbids name (own) (unrevealed)` so for example a wallet-recovering user would execute
`rpc getbids null true true`.
```
--> hsw-rpc getbids test-txt
[
{
"name": "test-txt",
"nameHash": "e4dfb97162995a696714a84f3bd3f242b02f5f071c1c6670a24f5ae1e1235007",
"prevout": {
"hash": "735060373e19caf8500eb050c456004069cb1edeebc689ee36c1bb0f5a45cd1b",
"index": 0
},
"value": 1000000, …
```

wallet: filter rpc getbids by unrevealed and return address

---

lib/protocol/networks.js

Closes #540 
The easyhandshake DNS seed was disabled over a year ago in bbac8dd943767da62e46e52f93227b3da1048e17 when the network protocol version was bumbed (easyhandshake stayed on the old code to act like a "bridge" if the network partitioned). I think it's safe to put it back.
Reviewers can test by:
- `rm ~/.hsd/hosts.json`
- clear out the contents of the array in https://github.com/handshake-org/hsd/blob/master/lib/net/seeds/main.js
- start `hsd`
These log messages should be expected:
```
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: hs-mainnet.bcoin.ninja.
[info] (hostlist) Resolving host: seed.easyhandshake.com.
...
[info] (net) Resolved 24 hosts from DNS seeds.
```
...followed by a healthy peer count and network …

net: restore easyhandshake dns seed

---

.github/workflows/docs.yml
.github/workflows/node.js.yml

Needed to prevent CI failures [like this one](https://github.com/handshake-org/hsd/runs/2834823661?check_suite_focus=true) in the future by locking down dependencies that can introduce subtle errors [like this](https://github.com/markedjs/marked/issues/2106).
https://github.com/pinheadmz/bsdoc
https://www.npmjs.com/package/@hns-dev/bsdoc

ci: switch to vendored jsdoc

---

lib/migrations/migrator.js
test/migrations-test.js

A user has already reported an issue with a deployment in which they use a single configuration file (a Dockerfile with command line options) that can end up being run on both brand new and old, not-yet-migrated nodes.
The problem is we currently throw an error if `--chain-migrate` is passed to a brand new node:
```
--> hsd --chain-migrate=2 --prefix=~/Desktop/hsd-fresh
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chaindb) Opening ChainDB...
Error: Database does not exist.
at ChainMigrator.migrate (/Users/matthewzipkin/Desktop/work/hsd/lib/migrations/migrator.js:143:13)
at async ChainDB.open (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chaindb.js:83:5)
at async Chain.open (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:86:5)
at …
```

migrations: ignore migration flag if db is brand new

---

lib/covenants/ownership.js
lib/wallet/client.js
lib/wallet/nodeclient.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/claim-test.js
test/ownership-test.js

Background: https://handshake.org/notice/2020-04-02-Inflation-Bug-Disclosure.html
Relevant section:
> NEW PROTOCOL RULES
> A CLAIM must commit to a mainnet block hash. By default, all claims commit to block 1. The existing rules already require that subsequent re-claims commit to higher block heights. This makes it easy to determine in the software when a claim is being re-submitted (commitHeight > 1). The following new rules are enforced by the soft-fork code:
> 
> • An initial CLAIM MUST commit to block 1.
> • An initial CLAIM MUST pay a fee less than 1,000 HNS.
> • A re-claim MUST pay the exact same fee as the initial CLAIM.
> • The fees from any re-claim MUST NOT be collected by the miner: they are "burned" or, more accurately, already exist in a previous block.
> • A re-claim can not …

wallet: enable re-claiming of reserved names using new protocol rules from recent soft fork

---

lib/hd/mnemonic.js
lib/wallet/http.js
lib/wallet/wallet.js
test/wallet-http-test.js
test/wallet-test.js

Closes https://github.com/handshake-org/hsd/issues/587
Once https://github.com/handshake-org/hs-client/pull/39 is merged together:
```sh
$ hsw-cli --network=regtest --id=cartera --language=spanish mkwallet
{
"network": "regtest",
"wid": 1,
"id": "cartera",
"watchOnly": false,
"accountDepth": 1,
"token": "251e4f2b6a238cf3491ee783bc2d0ab09a8aeed8fb81296cc81d1bbd026c1812",
"tokenDepth": 0,
"master": {
"encrypted": false
},
"balance": {
"account": -1,
"tx": 0,
"coin": 0,
"unconfirmed": 0,
"confirmed": 0,
"lockedUnconfirmed": 0,
"lockedConfirmed": 0
}
}
$ hsw-cli --network=regtest --id=cartera master
{
"encrypted": false,
"key": {
"xprivkey": "rprvKE8qsHtkmUxUSR1stB2VJX3ibU3WzvUWZXxrzTJph7Sy91AVQJwBPVdE9HxZEkH6MfeDME26YLtmUZ46p1EDpn2HV16rpFGyJ81A6ikrKxV4"
},
"mnemonic": {
"bits": 256, …
```

wallet: accept language option for mnemonic when creating new wallet

---

CHANGELOG.md
bench/nsec.js
lib/dns/common.js
lib/dns/nsec.js
lib/dns/resource.js
lib/dns/server.js
test/data/ns-icann.json
test/data/ns-names.json
test/ns-test.js
test/resource-test.js

This PR uses epsilon functions optimized for handshake root zone based on [RFC4470](https://tools.ietf.org/html/rfc4470) to find minimally covering NSEC records. 
Closes #574 and closes #513 (a minor change is needed in bns to check for bogus but shouldn't require other changes in hsd)
One issue with compact NSEC proofs is that due to qname minimization a compact proof may require multiple NODATA lookups `test.example.doesntexist` may need three lookups. The change to these proofs was adding a wildcard NSEC record to get NXDOMAIN responses. The response is a tiny bit larger (only for NXDOMAIN case) than compact proofs (~400 bytes vs. ~524 bytes for average length names) but covers all names underneath the TLD limits the number of proofs that need to be signed.
This PR fixes dnssec denial …

dns: fix root server dnssec proofs

---

lib/dns/server.js
test/ns-test.js

Closes https://github.com/handshake-org/hsd/issues/400
Also imports a fix from hnsd PR https://github.com/handshake-org/hnsd/pull/67 which returns empty SOA if `_synth` is queried by itself (encourages the recursive resolver to ask again with the full synth address)
Third commit adds newlines `\n\n` before DNS messages in the log. These messages are only printed at `--log-level=spam` anyway and improve readability a whole heckuva lot:

Use synth address for root server NS

---

CHANGELOG.md
lib/dns/server.js
lib/node/fullnode.js
lib/node/spvnode.js
test/ns-test.js

This PR allows for turning on/off `SIG(0)` for both the `RecursiveServer` and the `RootServer` with the options:
- `--rs-sig0 <true|false>`
- `--ns-sig0 <true|false>`
They both default to `true`, which is the current behavior.
This will make the removal of `SIG(0)` in the future easier as a release could turn it off once something better has been implemented.
The `sign` function is updated to check to make sure that `sig0` is enabled before signing. It needs to return the `msg` as `hsig.sign` returns a modified `msg`.
The `signSize` function is updated to check that `sig0` is enabled before returning its hard coded size. If it it not enabled, it will return 0.
You can see the code path that calls the `sign` function and the `signSize` function here: …

node: sig(0) config option

---

lib/primitives/tx.js
test/sighash-test.js

Description of this PR is also added as a comment in tx.js:
SIGHASH_NOINPUT does not commit to "this input's data", meaning the
outpoint and sequence of this input (only this input) is malleable.
However, our implementation neglects to also nullify the `prevouts`
and `sequences` values as specified in the original SIGHASH_NOINPUT BIP
https://blockstream.com/eltoo.pdf (appendix A).
This means that our NOINPUT is not useful, because even though it removes
this input's outpoint from one part of the signed data, it leaves it in
place in a different part, so it is still committed to by the signature.
Note that eltoo's NOINPUT and it's successor BIP-118 also make committing
to the witness script optional (in our code that value is called `prev`).
This may end up being not a big deal, adding …

test: sighash_noinput is not implemented correctly

---

lib/node/rpc.js

Just use `util.hex32` instead.
continues: #146

node-rpc: clean up hex32 method.

---

lib/dns/common.js
lib/dns/server.js
test/ns-test.js

The root server doesn't give proper negative answers for synth records. Asking a synth name for a TXT record it answers with an AAAA record:
```
dig @hsd-root _4o34e027000000000000000h24._synth. TXT +dnssec
_4o34e027000000000000000h24._synth. 21600 IN AAAA 2606:4700:4700::1111
```
Also querying `dig @hsd-root _synth. DS/NS` doesn't give proper NSECs which may be problematic for some recursive resolvers and ends up being SERVFAIL if queried from recursive. This PR fixes negative answers and also adds proper NSECs for _synth to make them more standards compliant/suitable for production use.

dns: fix negative answers & add non-existence proofs for _synth

---

lib/mempool/mempool.js
test/mempool-test.js

This is port of https://github.com/bcoin-org/bcoin/pull/641 by tynes in #153.
Reviewed for `hsd` usage of `getSpentView`, its same as `bcoin`.
Closes #153.
From commit message 8cecb6b6af9d1c39c87016b092251e57c3f2e4e1
```
Currently coinview does not account for spent coins in the mempool,
This does not create problems because we have additional checks in
right places which detect double spends, but technically
coinview should help you detect double spent in the mempool as well.
This way it will be compatible with chain.getCoinView.
getSpentView will still return all outputs that are available
in the mempool. (This could also return spentView from indexers if
available, this method is used by `signrawtransaction`.)
Port of bcoin commit: 32cba1bf4aa293bcf49c1849587dc1482ce98050 …
```

mempool: reflect spent coins in mempool coinview

---

test/airdrop-test.js
test/auction-reorg-test.js
test/auction-test.js
test/chain-test.js
test/invalid-reorg-test.js
test/mempool-test.js
test/miner-test.js
test/wallet-auction-test.js
test/wallet-test.js

Our tests don't need a lot of CPU work and spawning workers takes time. Machines with more cores will take more time spawning workers than the actual work. This issue came up in Bcoin as well on some CIs: https://github.com/bcoin-org/bcoin/pull/777

test: use fixed size 2 for workerpool.

---

lib/node/http.js
lib/wallet/http.js

https://github.com/bcoin-org/bweb/issues/10

add localhost to no-auth list

---

lib/blockchain/chaindb.js
lib/blockstore/file.js
lib/blockstore/level.js
test/blockstore-test.js
test/chain-blockstore-test.js
test/chain-migration-test.js

ChainDB and BlockStore are separate and committing to them is not really atomic,
so we need to make sure the order operations can handle failure at any step.
Previously blockstore writes and prunes would happen after the chaindb was
written, but that could lead to the situation where the blockstore did not
actually have a block but chaindb had the information.
This PR separates write and prune batches for the blockstore, so we can try
writing to blockstore first. In case writing to blockstore fails whole operation
will get aborted. Nothing gets written into the chaindb, so the information is
consistent. In case blockstore writes a block and then chaindb write fails,
we just get extra data in the blockstore. But most of the time, the same block
write will happen again (either main or alt …

blockstore - separate write and prune batches.

---

lib/primitives/tx.js

Found a minor mistake in JSDoc.
Removed browser folder left over from bcoin.

Removed browser folder and minor JSDoc changes

---

CHANGELOG.md
lib/net/pool.js
lib/node/fullnode.js
lib/node/spvnode.js
test/net-test.js

Closes https://github.com/handshake-org/hsd/pull/664
TODO:

net: propagate the user agent from node to pool

---

.github/workflows/docs.yml
.github/workflows/node.js.yml
package.json

[Node v18.0.0 (Current)](https://nodejs.org/en/blog/release/v18.0.0/)
Update LTS versions: https://nodejs.org/en/about/releases/

ci(tests): Update nodejs versions

---

CHANGELOG.md
lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/blockchain/migrations.js
lib/node/fullnode.js
lib/node/rpc.js
package-lock.json
package.json
test/chain-migration-test.js
test/chain-tree-compaction-test.js

Closes #660
Adds new rpc method `compacttree` which deletes from disk an enormous amount of historical data in the Urkel Tree that is only necessary in the case that a chain reorganization occurs deeper than ~288 blocks. Note that this condition also applies to blockchain-pruning nodes and in the event of such a deep reorg, a pruned node will fail into an unrecoverable state. Pruning is available as a configuration setting or can be executed while running with rpc `pruneblockchain`.
Since the tree is append-only, when an existing name is updated (anything from a REVEAL to a REGISTER to an UPDATE) the old data still remains on disk. A new tree node is written and some file pointers are shuffled around to determine the new root hash of the tree (which is committed to in a block header).
If …

[consensus] Enable Urkel Tree compaction

---

bin/node
bin/spvnode
lib/blockchain/chain.js
lib/errors.js
lib/hsd.js
lib/node/fullnode.js
lib/node/node.js
lib/node/spvnode.js
test/node-critical-error-test.js

Closes https://github.com/handshake-org/hsd/issues/642
(although there may be more places where this extreme action is warranted)
This PR adds a new test utility: RAMDisk. This is a cute trick where we create a virtual storage device in RAM that is really small (1 MB) then run a full node inside it until we fill up the disk. I tried to ensure that even in test suite failures we don't end up with a bunch of tiny volumes still mounted, but it may take some more work to make sure everything is super clean.
TODO:

Gracefully shut down node on critical errors like full disk

---

lib/wallet/walletdb.js
test/wallet-events-test.js

Closes #621.
Changes:
- Added an emit for `block connect` with `entry, txs`. The first arguemnt is not wallet becaue the block doesn't belong to a specific wallet (unlike other WalletDB events)
- Added emits for `block disconnect` with `entry`.
- Test for WalletDB emitting `tx`, `address`, `block connect`, and `block disconnect`
Used in Bob Wallet https://github.com/kyokan/bob-wallet/pull/469.

wallet: emit 'block connect' events

---

lib/blockchain/chaindb.js
test/chain-tree-compaction-test.js

If user kills the process before compaction is done on open, restarted node wont restart the compaction process until next interval. This makes sure we retry compaction after restart. If user somehow decided not to compact anymore and that's the reason of killing the process, they can just disable the compaction flag.

Restart compaction if full node quit before compaction finished.

---

lib/hd/mnemonic.js
test/mnemonic-test.js

`Mnemonic` verifies words by stripping each word, but stores phrase user input as-is.
And when `.toSeed()` is used by HD key: https://github.com/handshake-org/hsd/blob/ba949f348c58ec6a6a6231f411fe3caa7c5e7b80/lib/hd/private.js#L460
the new lines are included and these two phrases are considered different and create different wallets.
For context, a bob user faced this and got two different wallets.
This commit saves the validated words -> phrase instead of the phrase passed as argument.
Added a test that covers both single space and `\u3000` japanese space.

mnemonic: standardize phrase

---

lib/net/peer.js
lib/net/pool.js
lib/protocol/networks.js
test/net-spv-test.js

Related (at least partially) to #705.
This fixes 2 things:
- Nodes always expect a response when they ask for mempool
- If mempool is empty, another peer will not send any response, so the requesting node thinks the peer is stalling and disconnects after timeout (30 secs).
- **To fix:** removed mempool packet from addTimeout so the node doesn't wait for a response
- Also changed `requestMempool` to `true` on all networks (was only for regtest before). This makes SPV nodes request mempool on connecting to loader peers.
- Once a chain is reset, it tells the pool to force resync.
- But, `sendGetBlocks` has a check to see if it's a repeat request (if the `tip` and `stop` match the last time it had sent `getBlocks` to that peer)
- If it matches, then `getBlocks` is not sent and we don't get …

net: fixes for SPV

---

test/net-spv-test.js

Urkel nonexistence proofs have more than one flavor. This test checks both COLLISION (we ended on a leaf that wasnt the key we were searching for, actually a partial collision) and DEADEND (we hit a null node)

test: cover additional nonexistence proof

---

.github/workflows/docker.yml
docs/install.md

The images will be published to ghcr.io and available [here](https://github.com/handshake-org/hsd/packages).
Each new git tag will generate/replace:
Example tag: `v5.6.7`
* handshake-org/hsd:latest
* handshake-org/hsd:5.6.7
* handshake-org/hsd:5.6
* handshake-org/hsd:5
Merges to `master` generates:
* handshake-org/hsd:edge
Depends on #755

feat(Docker): publish docker images to ghcr.io and DockerHub

---

CHANGELOG.md
lib/wallet/rpc.js
lib/wallet/wallet.js
test/anyone-can-renew-test.js
test/interactive-swap-test.js
test/wallet-accounts-auction-test.js
test/wallet-auction-test.js
test/wallet-http-test.js
test/wallet-importname-test.js
test/wallet-rpc-test.js

Creates batching functions in the wallet and exposes two new RPC calls: `sendbatch` and `createbatch`. The argument is an array of "actions". Actions are an array that starts with a string indicating the action type (usually a covenant but could also be meta-covenant type like `CANCEL`) followed by the arguments expected by the corresponding `make___()` function.
Examples:
```
hsw-rpc sendbatch [['OPEN', 'menace'], ['OPEN', 'to'], ['OPEN', 'the'], ['OPEN', 'network']]
hsw-rpc sendbatch [['BID', 'menace', 100, 100], ['BID', 'to', 1, 2], ['BID', 'the', 30, 40], ['BID', 'network', 100, 100]]
hsw-rpc sendbatch [['REDEEM', 'menace'], ['REDEEM', 'to'], ['UPDATE', 'the', {"records":[]}], ['UPDATE', 'network', {"records":[]}]]
hsw-rpc sendbatch '[["OPEN", "heynicetomeetyou"], ["NONE", …
```

Wallet: create batch transactions with any combination of covenants

---

CHANGELOG.md
lib/net/pool.js
lib/node/rpc.js
test/auction-rpc-test.js

Closes https://github.com/handshake-org/hsd/issues/646
Also see https://github.com/kyokan/bob-wallet/pull/409
Restores SPV node RPC functionality for `getnameinfo` `getnameresource` `verifymessagewithname` and `getnamebyhash`.
Each of these rpcs now accepts an extra boolean parameter `safe`. When `true`, the node gets historical data from the "safe height" which is **the last tree root commitment with more than 12 confirmations**. This is obviously historical data that any full node will have locally, but is also data that can be retrieved from the p2p network by an SPV node. This is the exact same mechanism used by SPV (and hnsd) for light client name resolution.
Example:
```
hsd-rpc getnameinfo chaos
hsd-rpc getnameinfo chaos true
```
```
hsd-rpc getnameinfo chaos
hsd-rpc getnameinfo …
```

rpc/pool: use urkel proofs for namestate in spv mode

---

lib/net/pool.js
lib/wallet/nodeclient.js
test/node-spv-test.js

Covers part of #705
Adds new library function `watchName()` to `pool` where similar (internally unused) functions cover adding addresses and outpoints. Proves that importing name into wallet in SPV mode does automatically update the wallet's bloom filter, as well as the pool's bloom filter (which is the same literal object). Listens for `sendFilter` events to catch the filter update being sent by the spv node.

pool/wallet/spvnode: test imported names are added to filter and sent

---

CHANGELOG.md
lib/net/hostlist.js
lib/node/http.js
test/node-http-test.js
test/p2p-test.js

Closes https://github.com/handshake-org/hsd/issues/689
The issue is that the ports displayed in `info` are the *public* ports set by `--public-port` and `--public-brontide-port` not `--port` and `--brontide-port`. Public hosts and ports are what we advertise to peers when we are listening for inbound connections, this is the hostname that gets gossiped around the network. The other options set the *actual* host and port the server actually listens to 🤷‍♂️ 
- We will not advertise our own address unless `--listen=true`
- On mainnet (only) we will not advertise our own address unless an address is specifically passed with `--public-host`
- This behavior was added to hsd to prevent unreachable nodes from accidentally (user error) advertising
This PR adds some new fields to the `pool` object …

Clarify ports / public ports in node HTTP getinfo

---

.github/workflows/build.yml
CONTRIBUTING.md
Dockerfile
docs/install.md
test/net-lookup-test.js

Apparently, `--omit=dev` should be used over `--production`.

Fix npm warning

---

lib/wallet/rpc.js
test/wallet-rpc-test.js

Fixes #783.
A non-existent value was being passed to `Amount.coin()` for fee. `Details` has a `getFee()` only, not `.fee` unless it's in JSON form.
It only reached that if branch and errored when a "send" tx was queried (no ouptut path).
Fee is negative, TIL that's how it should be as per bitcoin docs too: https://developer.bitcoin.org/reference/rpc/gettransaction.html
```js
❯ hsw-cli --http-port 14039 rpc gettransaction d4769eac97426952183cb97b864af630e1707228f866941406b967e7c15a5862
{
"amount": -15,
"blockhash": "5a6b4320ad4b34bae89bd90ff0e5720fa940dfb8e81ac2abc273b0c736fe12b8",
"blocktime": 1671435071,
"txid": "d4769eac97426952183cb97b864af630e1707228f866941406b967e7c15a5862",
"walletconflicts": [],
"time": 1671435063,
"timereceived": 1671435063,
"bip125-replaceable": "no",
"details": …
```

wallet: use correct fee in rpc gettransaction

---

lib/primitives/tx.js
test/mempool-test.js

Users have been able to broadcast huge batches with 1,000 OPENs in a single TX. That would make an entire block invalid, so there's no reason to relay such a TX. We could also decide to add a POLICY rule that restricts this even further (the recent wallet batching work limits to like 200)

mempool: reject TXs that exceed consensus covenant block limits

---

lib/mempool/mempool.js
test/mempool-reorg-test.js
test/mempool-test.js

Minimal alternative to https://github.com/handshake-org/hsd/pull/773
fixes the bugs without adding additional complexity.

Mempool reorg covenants

---

lib/wallet/wallet.js
test/wallet-test.js

Remove fundlock force hack for the send.
It now will repeat the same signature as others like it. (open, bid, ..)

wallet: refactor createTX to be more flexible

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/rpc.js
lib/wallet/txdb.js
lib/wallet/wallet.js
test/anyone-can-renew-test.js
test/interactive-swap-test.js
test/net-spv-test.js
test/wallet-accounts-auction-test.js
test/wallet-auction-test.js
test/wallet-deepclean-test.js
test/wallet-importname-test.js
test/wallet-rescan-test.js
test/wallet-test.js

`force` option is leftover after refactors as far as I can see in the history.
As it is not used and no one knows why it was there, might as well clean up.

wallet: remove force option from wallet.makeOpen.

---

lib/mempool/mempool.js
test/mempool-invalidation-test.js

Claims if they get ignored in the `claimPeriod - 1` block and still are part the mempool - next block will be invalid as it will include claims (as they are in mempool).
This invalidates claims in the mempool.

Mempool invalidate claims when period ends.

---

CHANGELOG.md
bin/hsw-cli
lib/client/wallet.js
lib/wallet/account.js
lib/wallet/http.js
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/wallet-http-test.js

This is based on #796, so if it does not make it I can rebase on current master, but #796 makes it much easier.
Summary:
- Add modify account endpoint
- Change create account endpoint
- Remove wallet check-lookahead flag.
Note, this update changes existing API call for `createAccount`, which used to be `PUT /wallet/:id/account/:account`. Until now it was okay, even though it's not RESTish. But this PR adds ability to modify account, so these need to change:
- Create account becomes: `POST /wallet/:id/account/:account`
- `PUT /wallet/:id/account/:account` becomes MODIFY/UPDATE the existing account entry.
Currently, only thing that can be changed about account is `lookahead`.
This also deprecates `check-lookahead` which was used previously to max out lookahead for all the wallets. Now this …

Wallet http endpoint for updating account lookahead

---

lib/wallet/http.js

Noticed on previous pr.
Now revealAll will be similar to redeemAll.

wallet-http: reveals all now can be created without broadcasting.

---

lib/wallet/wallet.js

Reserve and rollout check is leftover from initial implementation, where bid was actually open. So this is minor clean up.

wallet: minor clean up

---

lib/wallet/wallet.js
test/wallet-auction-test.js
test/wallet-importnonce-test.js

Bid actions in `makeBatch` had their addresses overridden after nonce generation, making it impossible to recover the wallet with importnonce.
With this change, the address is derived and passed to make* so the correct address is used to generate nonces.
The test covers both `sendbid` and `sendbatch`.

wallet: fix makeBatch to generate addresses early

---

lib/mempool/contractstate.js
lib/primitives/covenant.js
test/mempool-invalidation-test.js

Add more contract invalidation tests.

mempool: more invalidation tests.

---

lib/node/rpc.js

- Added totalSigs property to the JSON response object
- Use getMultisig() function to return n value if available

rpc: Added totalSigs to JSON response for scriptToJSON

---

bin/hsd-cli
bin/hsw-cli

problem:
```sh
❯ hsd --memory --network regtest --api-key apikey
❯ hsd-cli -k apikey info
Error: Unauthorized (bad API key).
at NodeClient.request (/media/data/Projects/handshake/hsd/node_modules/bcurl/lib/client.js:221:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async CLI.getInfo (/media/data/Projects/handshake/hsd/bin/hsd-cli:82:18)
at async CLI.open (/media/data/Projects/handshake/hsd/bin/hsd-cli:233:9)
at async /media/data/Projects/handshake/hsd/bin/hsd-cli:262:3
```
moved from hs-client repo:
- https://github.com/handshake-org/hs-client/pull/53

bin: fix config api-key alias

---

docs/release-notes/release-notes-6.x.md
package-lock.json
package.json

[Release notes for v6.0.0-rc.1](https://github.com/handshake-org/hsd/blob/2cc7e94b00dc53be97c354bc7f7c5a2b759e62b3/docs/release-notes/release-notes-6.x.md)
Includes (some in v5.1.0 as well):
- #819
- #834
- #828
- #797
- #807
- #806
- #796
- #815
- #836
- #824
- #818
- #802
- #746
- #833
- #835
- #825
- #826
- #827
- #820
- #813
- #817
- #816
- #814
- #808
- #810
- #805
- #800

Release v6.0.0-rc.1

---

lib/blockchain/chain.js
lib/mining/miner.js
test/chain-icann-lockup-test.js

Currently, it is not possible to signal for deployments which are `force: false`. This PR changes that by reverting 2 previous commits:
- https://github.com/handshake-org/hsd/pull/583 - `chain.computeBlockVersion()`
- https://github.com/handshake-org/hsd/commit/5e20a5aaaa7d4254ba88b14acd3b85f025330029 - `MinerOptions.version`
The way it's supposed to work is:
- `chain.computeBlockVersion` opts into all deployments
- `GetBlockTemplate` then opts out for those not included in `rules`
But,
- `getwork` and other software (b/hstratum) that depend on `Miner` directly, do not opt out at all
- and implicitly signal for all
To prevent this, the 2 temporary measures taken ~3 years ago:
- hard-coded Miner (used by getwork) to version 0 to skip calculating from chain, and
- made …

Fix bip9 signalling

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/wallet.js
test/wallet-http-test.js

HTTP Endpoints that are responsible to directly sending transactions to the mempool (except send tx) - did not use fund lock to queue the requests to the wallet. What ends up happening if you are running automated scripts or send multiple requests at once - coins wont get marked as spent before another set of coins are selected. Resulting in conflicting transactions.
This makes sure every send* transaction:
- `POST /wallet/:id/open`
- `POST /wallet/:id/bid`
- `POST /wallet/:id/reveal`
- `POST /wallet/:id/redeem`
- `POST /wallet/:id/update`
- `POST /wallet/:id/renewal`
- `POST /wallet/:id/transfer`
- `POST /wallet/:id/cancel`
- `POST /wallet/:id/finalize`
- `POST /wallet/:id/revoke`
Uses fundlock until the coin is added to the txdb, before processing next HTTP request.
Expose `hardFee` as …

wallet-http: put send transaction endpoints behind fund locks.

---

.github/workflows/build.yml

- npm broke compatibility with older nodejs versions. No longer update npm. 
- add nodejs v20 to the matrix.

ci: no longer update npm on build.

---

test/data/script-tests.json
test/getwork-test.js
test/script-test.js

Add redundant script checks. They are already covered in script-tests.json
Add OP_CHECKLOCKTIMEVERIFY failure on negative locktime.

script: add redundant tests to math ops.

---

lib/covenants/namestate.js
test/namestate-test.js

Adds an expired state to the "stats" object, refactors the `toStats()` method in namestate.js.
```
"stats": {
"blocksSinceExpired": 21
}
```

namestate: improve "stats" object for transfers, expiry and revoke

---

lib/wallet/txdb.js
test/wallet-test.js

- Don't emit conflict event when transaction was not removed.
Port of https://github.com/bcoin-org/bcoin/pull/977

txdb: fix conflict event bug.

---

test/brontide-test.js

Closes #196.
Rebased port of #196.

tests: add unit tests for cipher state

---

test/auction-reorg-test.js
test/auction-test.js

Closes: #326
> It is much more useful to mine based
on the auction lengths instead of using
magic numbers. This allows the parameters
to be tweaked and then ran through the
test suite because it is possible to choose
parameters that do not allow the auctions
to work at all. The `Network.get` call
at the top of the file can be altered
to select a different network, such as
simnet.

test: abstract some mining heights

---

CHANGELOG.md
lib/wallet/layout.js
lib/wallet/migrations.js
lib/wallet/txdb.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/wallet-balance-test.js
test/wallet-migration-test.js
test/wallet-test.js

This PR attempts to cover balance tracking with tests and fix some edge cases.
This is based on the initial idea of #780 and tests from it.
But expands scope to cover all balances instead of lock/unlocked.
To do full review on the txdb balance states and cover all missing cases, I have created psuedo code like document that includes all the cases this PR covers and future updates that may happen to the txdb methods. All cases that are covered in this PR are marked as `checkbox`es in the document: https://gist.github.com/nodech/c943e7c50b300b0505cc9dfcae243d48
Suggestions to where to move this document or if it's useful to other developers are welcome here or on the document.
Next tasks (Not part of the PR), maybe create issues:
- Add 'missed credit' events

Txdb tests and updates

---

lib/covenants/rules.js
lib/mempool/mempoolentry.js
lib/mining/template.js
lib/primitives/address.js
lib/primitives/claim.js
lib/primitives/coin.js
lib/primitives/covenant.js
lib/primitives/outpoint.js
lib/primitives/output.js
lib/primitives/tx.js
lib/types.js
lib/wallet/wallet.js
test/anyone-can-renew-test.js
test/contractstate-test.js
test/interactive-swap-test.js
test/mempool-test.js
test/util/memwallet.js
test/wallet-http-test.js
test/wallet-test.js

Add helper methods on covenant for every type.
Part of #703 and #619

covenant: set methods on covenant.

---

CHANGELOG.md
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/walletdb.js
test/mempool-reorg-test.js
test/wallet-auction-test.js
test/wallet-events-test.js
test/wallet-migration-test.js
test/wallet-test.js

WalletDB `open` does not guarantee that the connection will open, if it's in standalone mode it may fail. So having the connect method inside `open` w/o any guarantees leaves any logic depending on it break. So it's much better to totally remove the concept of connection from open.
This changes several things:
- on open state cache needs to be recovered first (it was done on connect). If we don't have cache, then we initialize after on `connect` in the syncNode.
- migration can no longer start a rescan (and it may have failed previously on standalone) - it will instead rollback. 
- Added new flag `wallet-migration-no-rescan` - that tells to ignore rescan request from the migration.
Restructure the life-cycle methods for the walletdb.
- open - no longer calls connect - now emits `open` …

Wallet: Add open/close and connect/disconnect events.

---

lib/wallet/txdb.js
test/wallet-test.js

wallet: don't add coinbase txs to the pending list.

---

.eslintrc.json
lib/dns/resource.js
lib/primitives/airdropkey.js
lib/primitives/claim.js
lib/wallet/wallet.js
test/interactive-swap-test.js
test/util/memwallet.js
test/wallet-test.js

Update to latest bslint: 8.54 in the CI.
Update to es2020, more or less covered by minimum node v14.

lint: update to es2020. Use latest bslint

---

CHANGELOG.md
lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/wallet.js
lib/wallet/walletdb.js

In some cases loading wallet lazily is not good enough. if wallet open takes some time (e.g. because of the plugin) - first http request to the wallet will be responsible for opening the wallet. This PR allows users to load all wallets before HTTP service is started, guaranteeing the wallet will be available before starting HTTP server. 
By default this is set to `false`.

wallet: --preload-all option to load all wallet on open.

---

lib/wallet/walletdb.js
test/util/wallet.js
test/wallet-chainstate-test.js
test/wallet-test.js

This is part of review for this: https://github.com/handshake-org/hsd/issues/622
Only adds test cases to the codebase related to chain state. Does not fix/change anything.
Covers discovered bug which is currently skipped. There's bug related to corruption but it's currently skipped as it's not solved.
More discussion on the issue.

Wallet: add tests for the chain state and fix markState

---

lib/wallet/records.js
lib/wallet/txdb.js
lib/wallet/walletdb.js
test/mempool-invalidation-test.js
test/wallet-auction-test.js

Add more tests and deep-cross auction reorg edge case.

Cover reorg for double open index

---

lib/wallet/node.js
lib/wallet/plugin.js
lib/wallet/walletdb.js
test/chain-icann-lockup-test.js

After the ICANNLOCKUP has been locked in, walletdb can safely enable this feature and make sure it does not accidentally try to OPEN locked up names.
Wallets using `v6` of the `hsd`, can now also enable `icannlockup` for the wallet.

wallet: set icannlockup to true for wallets.

---

.eslintrc.json
jsdoc.json

Update ecmascript version in the linter.
Add `rm-imports` to the jsdoc. It allows us to annotate typedefs with typescript specific `import`s, w/o breaking the jsdoc generation. https://github.com/pinheadmz/bsdoc/pull/1
It just removes imports, as if they did not exist.
There's better "import-aliases" plugin also implemented in the bsdoc. But It needs more testing how better generated docs get and if there are any issues in the output. So we can upgrade later, after more experimenting with it.

pkg: update lint and docs.

---

test/dns-test.js

c-ares rewrote their DNS record parsing code and since c-ares 1.21 does not allow ANY records (https://github.com/c-ares/c-ares/pull/765). 
- Node.js v18 since v18.20
- Node.js v20 since v20.12
- Node.js v22
All above node.js versions are all using newer version c-ares, which breaks this code. After this issue is resolved in c-ares and node.js has upgraded c-ares we can enable this test case again.

test: disable dns-test until c-ares fix.

---

test/auction-reorg-test.js
test/auction-test.js
test/chain-checkpoints-test.js
test/chain-icann-lockup-test.js
test/claim-test.js
test/mempool-invalidation-test.js
test/mempool-test.js
test/txstart-test.js
test/util/stub.js
test/wallet-test.js

google DNS resolvers have limits on the size of the queries. cloudflare.com TXT sometimes is over that limit. Switch to cloudflare servers for now and make it configurable for tests.

test: change ownership resolver from google to cloudflare.

---

.eslintrc.json
CHANGELOG.md
lib/client/node.js
lib/client/wallet.js
test/node-http-test.js
test/util/node-context.js
test/wallet-http-test.js

- Add `getMempoolRejectionFilter` and `checkMempoolRejectionFilter` NodeClient
aliases.
- Add `getFee`, an HTTP alternative to estimateFee socket call.
- Add options to `getNames` for passing `own`.

Update wallet and node clients

---

lib/wallet/records.js
lib/wallet/txdb.js
lib/wallet/walletdb.js
test/wallet-records-test.js
test/wallet-test.js

Adds `mtime` option to the `TXRecord` and it no longer calls `util.now` directly, unless `mtime` is omitted. TXDB accepts option from WalletDB for nowFn.

Add nowFn to wdb options and txdb.

---

CHANGELOG.md
bin/hsw-cli
lib/client/wallet.js
lib/wallet/http.js
lib/wallet/wallet.js
lib/wallet/walletdb.js
test/node-rescan-test.js
test/wallet-chainstate-test.js
test/wallet-http-test.js
test/wallet-test.js

Make style consistent for methods and variables.

wallet-client: rename createAuctionTxs to createAuctionTXs.

---

lib/primitives/mtx.js
test/mtx-test.js

This is another simpler alternative to the: https://github.com/handshake-org/hsd/pull/666
It still gets rid of the inputs for the coinselection, but will make sure to check if coins are in coinview first and Coins list second.  This also fixes another issue, where existing inputs in the tx could get in conflict with passed inputs in the options.
Closes: #666
Closes: #639

MTX - Resolve coins from coinview as well during coinselection.

---

lib/wallet/wallet.js
test/wallet-auction-test.js

Linked inputs, such as REVEAL, REDEEM, REGISTER ... REVOKE, are tied to specific coins. Coins can't be used when they are either spent or spent in the mempool. Already spent errors are handled properly by checking existence of coins. 
Credits when they are in the wallets pending list (Most likely in the mempool as well) are not properly handled. Wallet will allow creation of covenant inputs, but it will fail later on coin selection. Coin selection can't use coins spent in pending, so it will fail with error: "Could not resolve preferred inputs". This should not happen again, and instead, new error will be thrown: "Credit is already pending for: ${name}"

Add more specific error when linked inputs are pending.

---

lib/protocol/networks.js

The way headers are requested for checkpoints is slightly different than normal - it does header requests in bulk between two checkpoints. Because the difference between 220k and 160k is 65k - it becomes bigger than general limit to the number of headers that can be requested: 51k.
This should resolve issue, as the gaps between them will become lower than 51k now.
Temporary solution for those who don't want to upgrade is to disable checkpoints until node reaches 175k blocks. (After 160k) Or upgrade to the release version with this PR.
Closes: https://github.com/handshake-org/hsd/issues/913
Closes: https://github.com/handshake-org/hsd/issues/909 (Even though it was resolved, probably the node got those 15k blocks eventually and slowly?)

Add checkpoint between 160k and 225k

---

.github/workflows/build.yml
.github/workflows/docker.yml
.github/workflows/docs.yml

- Update action versions
- Use v20 for coverage tests.
- Update npm for node v14 (to update node-gyp)
- Add 22.x to the matrix.

Update ci and add node v22

---

.npmignore
CHANGELOG.md
lib/wallet/http.js
lib/wallet/txdb.js
lib/wallet/wallet.js
test/wallet-http-test.js
test/wallet-test.js

- **minor**: Track and return total number of transactions being zapped. This can help users reason about the result of their actions, w/o this users can't track the results of the process.
- Don't accumulate hashes and return in wallet. This could lead to too much memory being used if the number of pending transactions is a lot. This list of hashes is not being used anywhere either.
- Fix Transaction Options not properly taking into account network of the node.

wallet-http: Return total number of transactions zapped.

---

lib/client/node.js
lib/client/wallet.js
lib/wallet/nodeclient.js
lib/wallet/nullclient.js
lib/wallet/txdb.js
lib/wallet/walletdb.js
test/util/node-context.js
test/util/nodes-context.js

Be more backwards compatible (bpkg parsers)

lib: don't use public class fields usage.

---

lib/blockchain/chain.js
lib/blockchain/chaindb.js
lib/blockchain/chainentry.js
lib/blockchain/common.js
lib/blockchain/migrations.js
lib/covenants/rules.js
lib/mempool/mempool.js
lib/migrations/migration.js
lib/migrations/migrator.js
lib/migrations/state.js
lib/net/pool.js
lib/node/spvnode.js
lib/wallet/client.js
lib/wallet/migrations.js
lib/wallet/nodeclient.js
lib/wallet/walletdb.js
test/chain-full-test.js

Some type clean ups that have been sitting in my stash.

update chain types

---

CHANGELOG.md
lib/wallet/http.js
lib/wallet/walletdb.js

Introduces endpoint to recalculate wallet balances
This PR adds an admin-only endpoint to recalculate balances across all wallets. This functionality was developed to address a balance calculation bug in a previous hsd version, but serves as a valuable maintenance tool for ensuring balance accuracy going forward.
- Adds a new `POST /recalculate-balances` endpoint (admin-only)
- Can be used to fix wallet balances if an automatic post-migration recalculation was interrupted
This is intended as a maintenance tool and should not be necessary during normal wallet operation.

wallet: recalculate-balances endpoint.

---

CHANGELOG.md
lib/blockchain/migrations.js
lib/migrations/migration.js
lib/migrations/migrator.js
lib/migrations/state.js
lib/wallet/migrations.js
test/chain-migration-test.js
test/data/migrations/chain-4-migrationstate-v1.json
test/data/migrations/wallet-6-migrationstate-v1.json
test/migrations-test.js
test/util/migrations.js
test/wallet-migration-test.js

Add in progress arbitrary data storage to the migrations. Long running processes may be interrupted and may not have simple way to recover last state. This should allow those migrations to store metadata to the db.
- Add version entry to the migration state. Repurpose unused 16 bits of flags into the version, that should allow conditional serialization of the migration state.
- Create and pass the migration context to the migrations instead of just passing Results.
- Migration context now contains state that will get committed after the migration is done, but also provides saveState for the data.

Migrations: Add in progress data to migration
