- lib/node/http.js
Fixes a bug introduced in #46. The code was also updated to match the
fix committed to bcoin.
> http: account for network when creating Address

- bin/node
- bin/spvnode
> bin: fix erroneous help message

- .gitignore
- package-lock.json
See: https://github.com/bcoin-org/bcoin/issues/619
> pkg: add lockfile

- lib/protocol/networks.js
port of https://github.com/bcoin-org/bcoin/pull/694
to eliminate the regtest seed, this cleans up the
logs when running a regtest node
> protocol: clear regtest seeds

- lib/wallet/wallet.js
See https://github.com/bcoin-org/bcoin/issues/661 for further details. I found this while testing reorganizations in bcoin.
> wallet: do not rebroadcast coinbase transactions

- lib/wallet/rpc.js
- lib/wallet/wallet.js
- test/wallet-test.js
Since we don't currently have any CI, a few linting errors sneaked into the codebase.
This pull request addresses the linting problems and now running `npm run lint` passes
without any errors. The tests all pass with `npm run test`
> all: fix linting errors

- test/mempool-test.js
When a new block is found, it should remove transactions
from the mempool that are included in the block and leave
transactions in the mempool that are not included in that
block.
This adds a unit test for the mempool that tests both of those cases
> test: mempool clears txs included in block

- README.md
This pull request adds a code coverage badge to the top of the `README`
> readme: add code coverage

- bench/bench.js
This commit ports over the bench helper script from coin seen here: https://github.com/bcoin-org/bcoin/blob/master/bench/bench.js
> bench: add bench helper script

- lib/node/http.js
Add additional fields to the response of node
HTTP `GET /`. The new fields can be found at
.mempool.{claims,airdrops,orphans}.
> node/http: add claims, airdrops, orphans

- lib/dns/records.js
Apply bugfix to `master` that is already in `testnet4-stable` branch.
> dns/records: bugfix assertion in TLSA JSON parsing

- lib/net/packets.js
- test/net-test.js
- test/sighash-test.js
Net tests with a couple of changes to packets for safety
Port of https://github.com/bcoin-org/bcoin/commit/a35516d4e0096314948a41ecba1e81c7467ceb61
Closes https://github.com/handshake-org/hsd/issues/197
> test: add lib/net tests

- lib/wallet/txdb.js
- lib/wallet/wallet.js
- test/wallet-test.js
port of https://github.com/bcoin-org/bcoin/pull/873
> wallet: prevent chains of unconfirmed spends exceeding policy limit

- lib/wallet/txdb.js
- test/wallet-auction-test.js
Port of https://github.com/handshake-org/hsd/pull/94 to simnet branch.
I think review is complete?
> wallet: allow duplicate open after auction expires

- test/wallet-auction-test.js
S̶i̶n̶c̶e̶ ̶t̶h̶i̶s̶ ̶t̶e̶s̶t̶ ̶c̶a̶s̶e̶ ̶r̶e̶q̶u̶i̶r̶e̶s̶ ̶m̶i̶n̶i̶n̶g̶ ̶c̶p̶u̶ ̶b̶l̶o̶c̶k̶s̶,̶ ̶i̶t̶ ̶s̶e̶e̶m̶s̶ ̶t̶o̶ ̶b̶e̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶#̶3̶5̶0̶ ̶i̶n̶ ̶c̶a̶u̶s̶i̶n̶g̶ ̶a̶ ̶i̶n̶c̶r̶e̶a̶s̶e̶ ̶i̶n̶ ̶t̶h̶e̶ ̶t̶i̶m̶e̶ ̶t̶a̶k̶e̶n̶,̶ ̶c̶a̶u̶s̶i̶n̶g̶ ̶t̶e̶s̶t̶ ̶t̶i̶m̶e̶o̶u̶t̶.̶ ̶F̶i̶x̶e̶d̶ ̶b̶y̶ ̶i̶n̶c̶r̶e̶a̶s̶i̶n̶g̶ ̶i̶t̶ ̶n̶o̶m̶i̶n̶a̶l̶l̶y̶ ̶f̶o̶r̶ ̶n̶o̶w̶,̶ ̶b̶u̶t̶ ̶w̶a̶r̶r̶a̶n̶t̶s̶ ̶a̶ ̶d̶e̶e̶p̶e̶r̶ ̶l̶o̶o̶k̶ ̶a̶s̶ ̶m̶e̶n̶t̶i̶o̶n̶e̶d̶ ̶i̶n̶ ̶t̶h̶e̶ ̶p̶r̶e̶v̶i̶o̶u̶s̶ ̶P̶R̶.̶
See comments below.
> test: wallet auction test - disable workerpool

- lib/wallet/http.js
> wallet-http: return 404 in getname

- lib/wallet/node.js
fixes #370; as @pinheadmz notes it was patched in bcoin here: https://github.com/bcoin-org/bcoin/pull/506/files
> fix wallet node config types

- Dockerfile
- README.md
> dockerfile: update and add docs.

- lib/wallet/http.js
- test/wallet-http-test.js
Similar to #460 but for nonce.
Related to kyokan/bob-wallet/issues/163
> Fix nonce with bid=0

- lib/covenants/rules.js
Add some comments to the file `lib/covenants/rules.js` and correct one comment that was not correct.
> rules: comments

- test/wallet-http-test.js
> update wallet http test to use hs-client

- test/mempool-test.js
I think this may be why CI failed on master.
> test: add more time between claim and block in mempool reorg test

- lib/wallet/http.js
remove witness options from create account and create wallet.
Small clean up PR.
> Remove witness option from wallet HTTP

- lib/node/rpc.js
- lib/wallet/rpc.js
Closes #561 
I was thinking to add parameter logs as well, but we need to consider for each rpc command which should not be logged.
E.g. private key import parameters
And I think in general any "sensitive" information should not be logged in any mode.
I could go through RPCs and filter commands where we can log parameters, if you think it will be valuable :).
---
As mentioned in #561, this is port of:
https://github.com/bcoin-org/bcoin/commit/7303d284d566eb609a41ecd378f137bfb1074b9a
> wallet rpc should log queries

- test/coin-test.js
- test/coins-test.js
- test/net-test.js
Just saw these and decided to clean up remaining "legacy" methods.
> minor cleanup.

- lib/wallet/txdb.js
- test/wallet-importname-test.js
Closes https://github.com/handshake-org/hsd/issues/595
> wallet: do not removeNameMap() in applyNameUndo()

- test/mempool-test.js
This is another fix to the mempool reorg test, which relies on an external Cloudflare DNSSEC signature. It has already been addressed in #518 and again in #531 but THIS TIME I think it's gonna work.
The problem is that when we get the Cloudflare RRSIG, it may have an inception timestamp incompatible with the blockchain timestamp rules (can not be older than `median time past` and can not be newer than `network.now() + 2 hours`)
To test, simulate the edge case by forcing the claim timestamp into the past by the perfect amount:
```diff
diff --git a/lib/covenants/ownership.js b/lib/covenants/ownership.js
index 3757f54b7..6879db61a 100644
--- a/lib/covenants/ownership.js
+++ b/lib/covenants/ownership.js
@@ -178,7 +178,7 @@ class Ownership extends BNSOwnership {
data.weak = weak; …
```
> Fix non-deterministic mempool reorg test (again!)

- lib/blockchain/chain.js
- lib/blockchain/chaindb.js
- lib/node/fullnode.js
- lib/node/spvnode.js
- test/chain-prune-test.js
closes https://github.com/handshake-org/hsd/issues/624
> chain: remove forceflags

- lib/blockchain/chain.js
- lib/protocol/networks.js
Long overdue PR to enable checkpoints on mainnet. Currently untested.
> Fix and enable checkpoints for mainnet (WIP)

- README.md
see https://github.com/handshake-org/handshake-org.github.io/issues/132
> README: switch IRC link to libera

- lib/mining/template.js
- lib/node/rpc.js
> node/miner: remove inflation bug softfork covert signaling

- lib/wallet/records.js
- lib/wallet/walletdb.js
- test/wallet-records-test.js
This is a port of a single line fix from #250 and expands on that and adds tests.
Tasks:
> Wallet record tests

- lib/wallet/http.js
Fixes the style issues in that PR.
Closes #392
> Export HTTP.TransactionOptions

- lib/blockchain/chain.js
- lib/primitives/block.js
- test/chain-test.js
- test/util/memwallet.js
Technically, this is consensus code but all I'm changing are the error messages, which are just printed to the debug log. Looks like some copy/paste went down in here, as well as updated tree interval settings. Just cleaning up...
TODO:
> chain: fix consensus errors and comments

- .github/workflows/node.js.yml
I'm trying to fix the [Source not available](https://coveralls.io/builds/45317392/source?filename=lib%2Fprotocol%2Fconsensus.js#L4720) from Coveralls.
> Update coveralls action

- lib/node/rpc.js
- lib/wallet/rpc.js
- test/wallet-rpc-test.js
> fix(rpc): Can't sign/verify with name before auction is closed.

- lib/covenants/namestate.js
- lib/wallet/wallet.js
- test/util/memwallet.js
No extra features, just refactoring.
Inspired on [a comment](https://github.com/handshake-org/hsd/pull/679#issuecomment-1003605385) from a previous PR.
> refactor: Use namestate methods for state comparison

- test/sighash-test.js
Due to how NOINPUT is implemented, nSequence for the given input
is rendered ineffective, this deviates from the original implementation
in the eltoo paper, and developers need to be aware about this little quirk.
> test: Added more tests to NOINPUT implementation

- test/wallet-unit-test.js
Port of #120 w/o changes to the test directory structure.
> test: wallet unit tests.

- .github/workflows/node.js.yml
- test/claim-test.js
- test/getwork-test.js
Currently adding only macos to the test.
Also:
- Run tests not only on master branch but others as well.
- Separate lint and doc lint
- Separate test coverage
- Add macos to the test matrix.
- Fix some failing tests.
> add macos to the test matrix.

- docs/release-notes/release-notes-v4.x-draft.md
- package-lock.json
- package.json
Check [Release Notes Draft](https://github.com/handshake-org/hsd/blob/8047df7130af7c00ba49d4fe7aac9ec797b23616/docs/release-notes/release-notes-v4.x-draft.md) (Draft because it's release candidate)
> Release v4.0.0-rc.1

- package-lock.json
- package.json
- test/anyone-can-renew-test.js
- test/auction-reorg-test.js
- test/auction-rpc-test.js
- test/auction-test.js
- test/chain-checkpoints-test.js
- test/chain-tree-compaction-test.js
- test/interactive-swap-test.js
- test/mempool-test.js
- test/wallet-accounts-auction-test.js
- test/wallet-auction-test.js
- test/wallet-importname-test.js
- test/wallet-rescan-test.js
- test/wallet-rpc-test.js
This PR is attempt to clean up failing test cases and all relevant dependencies.
*Notes: Removed windows once again, but here's the link of the node-gyp issue - https://github.com/nodejs/node-gyp/issues/2683*
> Update package and tests.

- bin/node
- bin/spvnode
First time pull-requesting. Hope this is right. Fixed typos in node and spvnode as indicated by @pinheadmz in Telegram.
> node+spvnode: typo fixes

- docs/install.md
finish fixing this: https://github.com/handshake-org/hsd/pull/755/commits/500eae03d79fd34e391455372e264e49f642cdae
> docs: run docker on mainnet and use host volume

- docs/install.md
f78947ec20f28f54a602a4d2d96ca537cec160b7  https://github.com/handshake-org/hsd/pull/776#issuecomment-1311934203
> Update minimum required Node.js version to 14

- docs/release-notes/release-notes-4.x.md
- Backport v4.x release
- ~Update node engine version to v14.~ (Moved to #790)
> Backport v4 release docs

- docs/release-process.md
Accumulate experience from our first release since release docs and update.
> Update release process.

- CHANGELOG.md
- lib/wallet/account.js
- lib/wallet/http.js
- lib/wallet/migrations.js
- lib/wallet/wallet.js
- lib/wallet/walletdb.js
- test/wallet-http-test.js
- test/wallet-migration-test.js
- test/wallet-unit-test.js
**NOTE This requires migrations so needs to land in 5.x**
If there are any breaking changes to layout we want in DB, this is probably good time.
> wallet: increase lookahead configuration to 2 ** 32.

- package-lock.json
- package.json
Update package dependencies and engine explicitly.
> update package dependencies.

- docs/release-notes/release-notes-5.x-draft.md
- package-lock.json
- package.json
[Draft for v5.0.0-rc.1](https://github.com/handshake-org/hsd/blob/20522550bfec7d8403c846e5f8f9c2915cb63124/docs/release-notes/release-notes-5.x-draft.md)
> Release 5.0.0-rc.1

- lib/protocol/networks.js
- test/auction-reorg-test.js
- test/auction-test.js
- test/chain-checkpoints-test.js
- test/claim-test.js
- test/mempool-test.js
- test/txstart-test.js
- test/wallet-test.js
Use latest checkpoint from: https://github.com/handshake-org/hsd/pull/785.
Currently last checkpoint is still at 100k blocks.
> Main net - update last checkpoint.

- test/anyone-can-renew-test.js
- test/blockstore-test.js
- test/interactive-swap-test.js
- test/wallet-rpc-test.js
- test/wallet-test.js
> test: fix .rejects usage.

- test/mempool-test.js
Clean up mempool-test a little bit.
> minor mempool test cleanup.

- lib/blockchain/chaindb.js
- lib/node/fullnode.js
- test/auction-reorg-test.js
- test/auction-test.js
- test/chain-full-test.js
- test/mempool-test.js
- test/txstart-test.js
- test/wallet-rescan-test.js
It was moved to different places for the verification.
> chain: clean up unused hardened option from getNameStatus.

- docs/release-process.md
https://github.com/handshake-org/hsd/pull/597#issuecomment-1635872519
> Update checkpoints guide in release-process.md

- docs/release-notes/release-notes-5.x.md
- lib/mempool/contractstate.js
- lib/node/rpc.js
- lib/primitives/covenant.js
- lib/protocol/networks.js
- lib/wallet/wallet.js
- package-lock.json
- package.json
- test/auction-reorg-test.js
- test/auction-test.js
- test/chain-checkpoints-test.js
- test/claim-test.js
- test/mempool-test.js
- test/txstart-test.js
- test/wallet-importnonce-test.js
- test/wallet-test.js
PRs:
- #805 (minor)
- #824 (minor)
- #825 (patch)
- #826 (patch)
>  Release v5.1.0

- bin/cli
- bin/hsd-rpc
- bin/hsw-rpc
see comment below.
~~Main PR in hs-client, go here for more info:~~
- ~~https://github.com/handshake-org/hs-client/pull/51~~
> bin: replace shell scripts with js require

- scripts/gen-hsclient.js
Instead of trying to remove master history from `hs-client`, append to it version by version. It will give better visibility to what happened even though it is auto-generated.
> Update hs-client generator

- docs/release-notes/release-notes-6.x.md
- lib/blockchain/chain.js
- lib/mining/miner.js
- package-lock.json
- package.json
- test/chain-icann-lockup-test.js
> Release v6.1.0

- lib/node/spvnode.js
- lib/protocol/networks.js
Closes https://github.com/handshake-org/hsd/issues/603
> pkg: clean up unused params.

- lib/blockchain/chain.js
Clean up the errors. No need for it to be critical.
> chain: remove unnecessary critical error.

- lib/wallet/txdb.js
- lib/wallet/wallet.js
Simple update to jsdocs and some switch/case styles for more complex blocks.
> wallet: fix batch styles and jsdocs.

- lib/net/seeds/main.js
16 GiB and 4 vCPU using the latest generation general purpose Amazon EC2 M7g instance in Mumbai. [Status Page](https://empty-bonus-92feac03.cronitorstatus.com) and Live Status Badge:   ![Handshake seed node Mumbai](https://cronitor.io/badges/6vhCDn/production/2bHaU9W85BCvBmbhzL_pf_2YzwY.svg)
See https://github.com/opensystm/handshake-micro-grants/issues/5 for more details.
> add a new permanently hard-coded seed node

- CHANGELOG.md
- lib/blockchain/chain.js
- lib/node/fullnode.js
- lib/node/http.js
- lib/node/spvnode.js
- test/node-http-test.js
- `GET /` or `getInfo()` now has more properties:
- `treeRootHeight` - height at which the block txns are accumulated in the current batch.
- `indexers`
- `indexTX` - is tx indexer enabled.
- `indexAddress` - is addr indexer enabled.
- `options` 
- `spv` is the Node SPV?
- `prune` does node have pruning enabled.
- `treeCompaction`
- `compacted` - whether tree is compacted or not.
- `compactOnInit` - is tree compaction on init enabled.
- `compactInterval` - what is the current compaction interval config.
- `nextCompaction` - when will the next compaction trigger after restart.
- `lastCompaction` - when was the last compaction run.
- #175
> Add node/chain parameters to the getInfo (`/`)

- package-lock.json
- package.json
Update bdb to include multi-byte keys.
Update package.json with latest patch versions.
> Update bdb and other deps.

- docs/release-notes/release-notes-7.x.md
- package-lock.json
- package.json
[Release notes for v7.0.0-rc.1](https://github.com/handshake-org/hsd/blob/1dbaac07f9391d4548a3513aa4a0a60a82994fa3/docs/release-notes/release-notes-7.x.md)
Includes:
- #888
- #896
- #899
- #883
- #782
- #859
- #882
- #885
- #856
- #803
- #869
- #866
- #845
- #900
- #906
- #884
- #904
- #902
- #901
- #898
- #897
- #895
- #893
- #887
- #881
- #875
- #879
- #870
- #876
- #858
- #871
- #873
- #861
- #868
- #860
- #863
- #865
- #853
- #852
- #555
- #851
- #850
- #849
- #844
>  Release v7.0.0-rc.1

- docs/release-notes/release-notes-7.x.md
- lib/protocol/networks.js
- package-lock.json
- package.json
[Release notes](https://github.com/handshake-org/hsd/blob/21aae5c895bd88af924ad2dce584c2f1b2dbab2f/docs/release-notes/release-notes-7.x.md)
Added after v7.0.0:
- #914
> Release v7.0.1

- lib/client/wallet.js
- lib/wallet/http.js
- test/wallet-http-test.js
Similar to getWalletStates, own will return 404 if namestate is not owned.
> wallet-http: Add own parameter to the getName.

- lib/wallet/http.js
- lib/wallet/masterkey.js
- test/wallet-http-test.js
> wallet-http: validate timeouts and make default explicit.
